export type MembersBannerType =
  | 'ORDER_MOBILE_KURLY_MEMBERS_COUPON'
  | 'ORDER_PC_KURLY_MEMBERS_COUPON'
  | 'ORDER_MOBILE_KURLY_MEMBERS_COUPON_BOTTOM'
  | 'ORDER_PC_KURLY_MEMBERS_COUPON_BOTTOM'
  | 'ORDER_MOBILE_KURLY_MEMBERS_ORDER_INFO_BOTTOM'
  | 'ORDER_PC_KURLY_MEMBERS_ORDER_INFO_BOTTOM'
  | 'ORDER_KURLYPAY_KURLY_MEMBERS_BANNER_MOBILE'
  | 'ORDER_KURLYPAY_KURLY_MEMBERS_BANNER_PC';

export const MEMBERS_BANNER = {
  MO_COUPON_LIST: 'ORDER_MOBILE_KURLY_MEMBERS_COUPON',
  PC_COUPON_LIST: 'ORDER_PC_KURLY_MEMBERS_COUPON',
  MO_COUPON: 'ORDER_MOBILE_KURLY_MEMBERS_COUPON_BOTTOM',
  PC_COUPON: 'ORDER_PC_KURLY_MEMBERS_COUPON_BOTTOM',
  MO_TOTAL_PRICE: 'ORDER_MOBILE_KURLY_MEMBERS_ORDER_INFO_BOTTOM',
  PC_TOTAL_PRICE: 'ORDER_PC_KURLY_MEMBERS_ORDER_INFO_BOTTOM',
  MO_KURLY_PAY: 'ORDER_KURLYPAY_KURLY_MEMBERS_BANNER_MOBILE',
  PC_KURLY_PAY: 'ORDER_KURLYPAY_KURLY_MEMBERS_BANNER_PC',
} as const;
