export const productDetailFixture = {
  no: 5060366,
  name: '[퀴네] 치폴레 버거 스타일 소스',
  shortDescription: '어디에나 잘 어울리는 만능소스',
  isSoldOut: false,
  soldOutText: '',
  notSalesText: '',
  extraInfos: [],
  deliveryTypeNames: ['샛별배송'],
  isReservable: false,
  reservationPossibleDates: null,
  basePrice: 4900,
  retailPrice: null,
  discountedPrice: 4200,
  discountRate: 14,
  isExpectedPoint: true,
  expectedPoint: 0,
  expectedPointRatio: 0,
  isDirectOrder: false,
  directOrderType: 'DEFAULT',
  normalOrderPolicy: {
    directOrderType: 'DEFAULT',
  },
  giftOrderPolicy: {
    directOrderType: 'SINGLE_DIRECT_ORDER',
  },
  minEa: 1,
  maxEa: null,
  canRestockNotify: true,
  isMultiplePrice: false,
  mainImageUrl: 'https://img-cf.kurly.com/shop/data/goods/1602045218106l0.jpg',
  shareImageUrl: 'https://img-cf.kurly.com/shop/data/goods/1602045218764z0.jpg',
  originalImageUrl: 'https://img-cf.kurly.com/shop/data/goods/1602045218106l0.jpg',
  legacyPromotion: null,
  isPurchaseStatus: true,
  isGiftable: false,
  isOnlyAdult: false,
  isGroupProduct: false,
  groupProducts: {
    groupKeys: [],
    groupMembers: [],
  },
  productNotice: [
    {
      dealProductNo: null,
      dealProductName: null,
      notices: [
        {
          title: '식품의유형',
          description: '상품설명 및 상품이미지 참조',
        },
        {
          title: '생산자및소재지(수입품의경우생산자,수입자및제조국)',
          description: '상품설명 및 상품이미지 참조',
        },
        {
          title: '제조연월일,유통기한또는품질유지기한',
          description: '제품 별도 라벨 표기 참조',
        },
        {
          title: '포장단위별용량(중량),수량',
          description: '상품설명 및 상품이미지 참조',
        },
        {
          title: '원재료명및함량(농수산물의원산지표시에관한법률에따른원산지표시포함)',
          description: '상품설명 및 상품이미지 참조',
        },
        {
          title: '영양성분(식품위생법에따른영양성분표시대상식품에한함)',
          description: '상품설명 및 상품이미지 참조',
        },
        {
          title: '유전자변형식품에해당하는경우의표시',
          description: '해당사항 없음',
        },
        {
          title: '영유아식또는체중조절식품등에해당하는경우표시광고사전심의필유무및부작용발생가능성',
          description: '해당사항 없음',
        },
        {
          title: '수입식품에해당하는경우“식품위생법에따른수입신고를필함＂의문구',
          description: '식품위생법에 따른 수입신고를 필함',
        },
        {
          title: '소비자상담관련전화번호',
          description: '컬리 고객행복센터 (1644-1107)',
        },
      ],
    },
  ],
  storageType: ['AMBIENT_TEMPERATURE'],
  exceptionLabel: null,
  reviewCount: 2093,
  guides: [],
  todayBrix: null,
  salesUnit: '1병',
  volume: '235ml',
  expirationDate: null,
  productOrigin: '상세페이지 별도표기',
  allergy: '-토마토,우유함유',
  afterSaleServiceInfo: {
    contactNumber: '',
    information: '',
  },
  sellerNames: ['컬리'],
  productDetail: {
    legacyContent:
      '<div class=\'goods_wrap\'> <div class="goods_intro"> <div class="pic"> <img src="https://img-cf.kurly.com/shop/data/goodsview/20201007/gv40000125807_1.jpg"> </div> <div class="context last"> <h3> <small>어디에나 잘 어울리는 만능 소스</small> [퀴네]<br /> 치폴레 버거 스타일 소스 </h3> <p class="words">늘 똑같은 요리를 색다르게 즐기고 싶은 분들이라면, 컬리가 준비한 드레싱이 반갑게 느껴지실 거예요. 유럽을 넘어 전 세계에 각종 소스류를 선보이는 브랜드, 독일 퀴네 사의 제품입니다. 이번에 만나 볼 제품은 버거 스타일의 치폴레 소스예요. 크리미한 질감에, 마치 케첩과 마요네즈를 섞은 듯 새콤하면서도 고소한 맛이 느껴지죠. 햄버거, 샌드위치 등을 만들 때나 감칠맛 나는 디핑 소스가 필요한 순간 활용해 보세요.</p> </div> </div> <div class="goods_point"> <h3><span>Kurly\'s Check Point</span></h3> <div class="context last"> <div class="pic"> <img src="https://img-cf.kurly.com/shop/data/goodsview/20201007/gv00000125808_2.jpg"> </div> </div> </div><div class=\'goods_pick\'><h3><span>Kurly’s Pick</span></h3> <div class="context last"> <p class="words"> <strong class="sub_tit"> <span class="option_tit">치폴레 버거 스타일 소스</span></strong> <b>&#12539;용량</b> : 1병(235mL)<br /> <b>&#12539;특징</b> : 토마토퓨레에 식초, 오이, 파프리카, 겨자씨, 치폴레고추 등을 넣어 만든 버거 스타일의 치폴레 소스예요.<br /> <b>&#12539;활용팁 </b>: 빵 위에 소스를 바른 다음 갖은 재료를 더해 햄버거, 샌드위치를 만들어 보세요. 양배추 샐러드에 듬뿍 뿌려 먹기에도 좋답니다. <br /> <b>&#12539;보관법</b> : 직사광선을 피해 건조하고 서늘한 곳에서 보관해 주세요. 개봉 후에는 잘 밀봉하여 냉장실에서 보관해 주세요.<br /> </p> </div>  </div></div>',
    legacyPiImages: ['https://img-cf.kurly.com/shop/data/goodsview/20220113/gv10000267350_2.jpg'],
    legacyEventBanner: '',
    content: [],
  },
  memberBenefit: {
    name: '',
    expectedPointRatio: 0,
  },
  memberCoupon: {
    newbieLimitDatetime: null,
    newbieMinPrice: 0,
  },
  dealProducts: [
    {
      no: 10060366,
      name: '[퀴네] 치폴레 버거 스타일 소스',
      isExpectedPoint: true,
      expectedPoint: 0,
      expectedPointRatio: 0,
      basePrice: 4900,
      retailPrice: null,
      discountedPrice: 4200,
      discountRate: 14,
      buyUnit: 1,
      isSoldOut: false,
      minEa: 1,
      maxEa: null,
      canRestockNotify: true,
      isPurchaseStatus: true,
      isGiftable: false,
      isOnlyAdult: false,
      masterProductCode: 'MK0000060366',
      masterProductName: '[퀴네] 치폴레 버거 스타일 소스',
    },
  ],
  isInquiryWritable: true,
  isReviewWritable: true,
  changeATFOption: false,
};
