name: SI

on:
  push:
    branches: [sample]

jobs:
  setup:
    name: Common Setup
    uses: thefarmersfront/kurly-web-workflows/.github/workflows/set-common-env-variables.yaml@main
    with:
      NODE_VERSION: 14.16.1

  lint:
    name: Run Lint
    runs-on: sre-runner
    strategy:
      matrix:
        node-version: [14.16.1]
    needs: [setup]
    steps:
      - name: Debug
        run: |
          echo "${{ needs.setup.outputs.REPOSITORY_NAME }}"
          echo "${{ needs.setup.outputs.PROJECT_ID }}"
          echo "${{ needs.setup.outputs.SHA_SHORT }}"
          echo "${{ needs.setup.outputs.COMMIT_MESSAGE }}"
          echo "${{ needs.setup.outputs.CACHE_PACKAGES_PATH }}"
          echo "${{ needs.setup.outputs.CACHE_PACKAGES_KEY }}"
          echo "${{ needs.setup.outputs.RELEASE_VERSION }}"

      - name: Checkout Source Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js Version - ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Setup NPM Cache
        id: cache-node-modules
        uses: maxnowack/local-cache@v2
        with:
          path: ${{ needs.setup.outputs.CACHE_PACKAGES_PATH }}
          key: ${{ needs.setup.outputs.CACHE_PACKAGES_KEY }}

      - name: Send Slack
        id: slack
        uses: slackapi/slack-github-action@v1.24.0
        with:
          payload: |
            {
              "text": "Test : Commit message is `${{ needs.setup.outputs.COMMIT_MESSAGE }}`. TAG VERSION is  `stg-${{ needs.setup.outputs.SHA_SHORT }}`."
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
