/**
 * 배송유형
 *
 * DAWN 샛별배송
 * DAY_PARCEL 하루배송
 * MANUAL_DAY_PARCEL 하루배송(샛별지역)
 * GOURMET_DELIVERY 미식딜리버리
 * NORMAL_PARCEL 판매자배송
 * INSTALLATION_DELIVERY 설치배송
 * ONLINE_TICKET 무배송(온라인 교환권)
 * AIRLINE_TICKET 무배송(항공권)
 * SELF_PICKUP_WINE 무배송(셀프픽업-와인)
 * QUICK_DELIVERY 퀵배송
 * NOW_DELIVERY 나우배송
 * INTERNATIONAL_DIRECT 해외직배송
 */

const DELIVERY_LABELS = {
  DAWN: '샛별배송',
  DAY_PARCEL: '하루배송',
  MANUAL_DAY_PARCEL: '하루배송',
  GOURMET_DELIVERY: '미식딜리버리',
  NORMAL_PARCEL: '판매자배송',
  INSTALLATION_DELIVERY: '설치배송',
  ONLINE_TICKET: '온라인교환권',
  AIRLINE_TICKET: '항공권',
  SELF_PICKUP_WINE: '셀프픽업',
  QUICK_DELIVERY: '퀵배송',
  NOW_DELIVERY: '나우배송',
  INTERNATIONAL_DIRECT: '해외직배송',
  COMBINED_ORDER: '합주문',
} as const;

const DELIVERY_POLICIES = {
  DAWN: DELIVERY_LABELS.DAWN,
  DAY_PARCEL: DELIVERY_LABELS.DAY_PARCEL,
  MANUAL_DAY_PARCEL: DELIVERY_LABELS.MANUAL_DAY_PARCEL,
  GOURMET_DELIVERY: DELIVERY_LABELS.GOURMET_DELIVERY,
  NORMAL_PARCEL: DELIVERY_LABELS.NORMAL_PARCEL,
  INSTALLATION_DELIVERY: DELIVERY_LABELS.INSTALLATION_DELIVERY,
  ONLINE_TICKET: DELIVERY_LABELS.ONLINE_TICKET,
  AIRLINE_TICKET: DELIVERY_LABELS.AIRLINE_TICKET,
  SELF_PICKUP_WINE: DELIVERY_LABELS.SELF_PICKUP_WINE,
  QUICK_DELIVERY: DELIVERY_LABELS.QUICK_DELIVERY,
  NOW_DELIVERY: DELIVERY_LABELS.NOW_DELIVERY,
  INTERNATIONAL_DIRECT: DELIVERY_LABELS.INTERNATIONAL_DIRECT,
  COMBINED_ORDER: DELIVERY_LABELS.COMBINED_ORDER,
} as const;

type DeliveryPolicies = typeof DELIVERY_POLICIES[keyof typeof DELIVERY_POLICIES];

const CART_DELIVERY_TYPE = {
  DAWN: 'DAWN',
  DAY_PARCEL: 'DAY_PARCEL',
  MANUAL_DAY_PARCEL: 'MANUAL_DAY_PARCEL',
  GOURMET_DELIVERY: 'GOURMET_DELIVERY',
  NORMAL_PARCEL: 'NORMAL_PARCEL',
  INSTALLATION_DELIVERY: 'INSTALLATION_DELIVERY',
  ONLINE_TICKET: 'ONLINE_TICKET',
  AIRLINE_TICKET: 'AIRLINE_TICKET',
  SELF_PICKUP_WINE: 'SELF_PICKUP_WINE',
  QUICK_DELIVERY: 'QUICK_DELIVERY',
  NOW_DELIVERY: 'NOW_DELIVERY',
  INTERNATIONAL_DIRECT: 'INTERNATIONAL_DIRECT',
} as const;

type CartDeliveryType = typeof CART_DELIVERY_TYPE[keyof typeof CART_DELIVERY_TYPE];

export { CART_DELIVERY_TYPE, DELIVERY_POLICIES };

export type { DeliveryPolicies, CartDeliveryType };
