import { ScreenName } from '.';

export const BROWSE_SCREEN_NAMES = new Set([
  ScreenName.BARGAIN,
  ScreenName.CATEGORY,
  ScreenName.CATEGORY_PRODUCT_LIST,
  ScreenName.EVENT_LIST,
  ScreenName.BRAND_LIST,
  ScreenName.BENEFIT_LIST,
  ScreenName.KURLY_PASS_GUIDE,
  ScreenName.MY_KURLY,
  ScreenName.MY_REVIEW_HISTORY,
  ScreenName.MY_REVIEWABLE_LIST,
  ScreenName.NEW_PRODUCT,
  ScreenName.POPULAR_PRODUCT,
  ScreenName.RECIPE_DETAIL,
  ScreenName.RECOMMENDATION,
  ScreenName.SEARCH,
  ScreenName.SEARCH_PRODUCT_LIST,
  ScreenName.STARRED,
  ScreenName.PICK_LIST,
  ScreenName.GIFT_LIST,
  ScreenName.GIFT_HISTORY,
  ScreenName.PROFILE_SETTING_SUCCESS,
  ScreenName.FREQUENTLY_PURCHASE_PRODUCT_HISTORY,
  ScreenName.ORDER_SHEET_DETAIL,
  ScreenName.CAROUSEL_LIST,
]);
