import { ReviewStatus } from '../../../shared/enums';
import { ORDER_STATUS } from '../../common/constants/OrderStatus';
import { STATUS } from '../../common/constants/Status';
import { STORAGE_TYPE } from '../../common/constants/StorageType';
import { DeliveryPolicy } from '../../common/interface/DeliveryGroup';

export const ORDER_LIST_GROUP_ORDER_PACKING_TYPE_SINGLE = {
  groupOrderNo: 2341610220002,
  paymentCompletedAt: '2024-05-09T10:22:44+09:00',
  deliveryGroups: [
    {
      orderNos: [1715217749001],
      deliveryPolicy: '샛별배송' as DeliveryPolicy,
      partnerName: '컬리',
      deliveryMessage: '5월 10일(금) 도착 예정',
      orderStatus: ORDER_STATUS.주문완료,
      deliveryCompletedImageUrl: null,
      dealProducts: [
        {
          dealProductNo: 1000318473,
          dealProductName: '[구씨반가] 송이버섯 들깨탕',
          contentsProductNo: 1000318474,
          contentsProductName: '[구씨반가] 송이버섯 들깨탕',
          quantity: 1,
          displayPrice: 13400,
          displayDiscountPrice: 0,
          paymentPrice: 13400,
          imageUrl:
            'https://product-image-stg.kurly.com/cdn-cgi/image/width=120,height=156,fit=crop,quality=85/product/image/5cc33a41-b9f7-491f-b91d-407d17f8c1de.png',
          reviewStatusType: ReviewStatus.HIDDEN,
          storageType: STORAGE_TYPE.냉동,
          status: STATUS.PRODUCING,
          isGiveawayProduct: false,
          invoice: null,
        },
      ],
      isSelfCancelable: false,
      invoices: [],
    },
    {
      orderNos: [1715217749001],
      deliveryPolicy: '샛별배송' as DeliveryPolicy,
      partnerName: '컬리',
      deliveryMessage: '5월 10일(금) 도착 예정',
      orderStatus: ORDER_STATUS.취소완료,
      deliveryCompletedImageUrl: null,
      dealProducts: [
        {
          dealProductNo: 1000318468,
          dealProductName: '[연세우유 x 마켓컬리] 전용목장우유 900mL',
          contentsProductNo: 1000318469,
          contentsProductName: '[연세우유 x 마켓컬리] 전용목장우유 900mL',
          quantity: 1,
          displayPrice: 5000,
          displayDiscountPrice: 0,
          paymentPrice: 5000,
          imageUrl:
            'https://product-image-stg.kurly.com/cdn-cgi/image/width=120,height=156,fit=crop,quality=85/product/image/cedb93ca-d8b4-4f72-b50f-620a38cfd46a.png',
          reviewStatusType: ReviewStatus.HIDDEN,
          storageType: STORAGE_TYPE.냉동,
          status: STATUS.REFUNDED,
          isGiveawayProduct: false,
          invoice: null,
        },
      ],
      isSelfCancelable: false,
      invoices: [],
    },
    {
      orderNos: [1713932721001],
      deliveryPolicy: '판매자배송' as DeliveryPolicy,
      partnerName: '유아월드2222',
      deliveryMessage: '',
      orderStatus: ORDER_STATUS.배송완료,
      deliveryCompletedImageUrl: null,
      dealProducts: [
        {
          dealProductNo: 1000309995,
          dealProductName: '3P - 택배 (S)',
          contentsProductNo: 1000309996,
          contentsProductName: '3P - 택배',
          quantity: 1,
          displayPrice: 100,
          displayDiscountPrice: 0,
          paymentPrice: 0,
          imageUrl:
            'https://third-party-file-dev.kurly.com/cdn-cgi/image/width=120,height=156,fit=crop,quality=85/files/132f09ae-6a44-48af-abc1-8ffa3d5c3d22/a4e6e5fd-8920-40f7-b86f-aab6cbd3cbdf.jpeg',
          reviewStatusType: ReviewStatus.HIDDEN,
          storageType: STORAGE_TYPE.냉동,
          status: STATUS.COMPLETED,
          isGiveawayProduct: false,
          invoice: null,
        },
      ],
      isSelfCancelable: true,
      invoices: [],
    },
  ],
  isSelfCancelable: false,
};

export const ORDER_LIST_GROUP_ORDER_PACKING_TYPE_MILTI = {
  groupOrderNo: 2341518570001,
  paymentCompletedAt: '2024-05-08T18:57:20+09:00',
  deliveryGroups: [
    {
      orderNos: [1715162239001, 1715162239001],
      deliveryPolicy: '샛별배송' as DeliveryPolicy,
      partnerName: '컬리',
      deliveryMessage: '5월 09일(목) 도착 예정',
      orderStatus: ORDER_STATUS.배송준비중,
      deliveryCompletedImageUrl: null,
      dealProducts: [
        {
          dealProductNo: 1000318473,
          dealProductName: '[구씨반가] 송이버섯 들깨탕',
          contentsProductNo: 1000318474,
          contentsProductName: '[구씨반가] 송이버섯 들깨탕',
          quantity: 1,
          displayPrice: 13400,
          displayDiscountPrice: 0,
          paymentPrice: 13400,
          imageUrl:
            'https://product-image-stg.kurly.com/cdn-cgi/image/width=120,height=156,fit=crop,quality=85/product/image/5cc33a41-b9f7-491f-b91d-407d17f8c1de.png',
          reviewStatusType: ReviewStatus.HIDDEN,
          storageType: STORAGE_TYPE.냉동,
          status: STATUS.COMPLETED,
          isGiveawayProduct: false,
          invoice: null,
        },
        {
          dealProductNo: 1000318468,
          dealProductName: '[연세우유 x 마켓컬리] 전용목장우유 900mL',
          contentsProductNo: 1000318469,
          contentsProductName: '[연세우유 x 마켓컬리] 전용목장우유 900mL',
          quantity: 1,
          displayPrice: 5000,
          displayDiscountPrice: 0,
          paymentPrice: 0,
          imageUrl:
            'https://product-image-stg.kurly.com/cdn-cgi/image/width=120,height=156,fit=crop,quality=85/product/image/cedb93ca-d8b4-4f72-b50f-620a38cfd46a.png',
          reviewStatusType: ReviewStatus.HIDDEN,
          storageType: STORAGE_TYPE.냉동,
          status: STATUS.REFUND_REQUESTED,
          isGiveawayProduct: false,
          invoice: null,
        },
        {
          dealProductNo: 1000318473,
          dealProductName: '[구씨반가] 송이버섯 들깨탕',
          contentsProductNo: 1000318474,
          contentsProductName: '[구씨반가] 송이버섯 들깨탕',
          quantity: 1,
          displayPrice: 13400,
          displayDiscountPrice: 0,
          paymentPrice: 0,
          imageUrl:
            'https://product-image-stg.kurly.com/cdn-cgi/image/width=120,height=156,fit=crop,quality=85/product/image/5cc33a41-b9f7-491f-b91d-407d17f8c1de.png',
          reviewStatusType: ReviewStatus.HIDDEN,
          storageType: STORAGE_TYPE.냉동,
          status: STATUS.REFUND_REQUESTED,
          isGiveawayProduct: false,
          invoice: null,
        },
        {
          dealProductNo: 1000309995,
          dealProductName: '3P - 택배 (S)',
          contentsProductNo: 1000309996,
          contentsProductName: '3P - 택배',
          quantity: 1,
          displayPrice: 100,
          displayDiscountPrice: 0,
          paymentPrice: 0,
          imageUrl:
            'https://third-party-file-dev.kurly.com/cdn-cgi/image/width=120,height=156,fit=crop,quality=85/files/132f09ae-6a44-48af-abc1-8ffa3d5c3d22/a4e6e5fd-8920-40f7-b86f-aab6cbd3cbdf.jpeg',
          reviewStatusType: ReviewStatus.HIDDEN,
          storageType: STORAGE_TYPE.냉동,
          status: STATUS.COMPLETED,
          isGiveawayProduct: false,
          invoice: null,
        },
        {
          dealProductNo: 1000309995,
          dealProductName: '3P - 택배 (S)',
          contentsProductNo: 1000309996,
          contentsProductName: '3P - 택배',
          quantity: 1,
          displayPrice: 100,
          displayDiscountPrice: 0,
          paymentPrice: 0,
          imageUrl:
            'https://third-party-file-dev.kurly.com/cdn-cgi/image/width=120,height=156,fit=crop,quality=85/files/132f09ae-6a44-48af-abc1-8ffa3d5c3d22/a4e6e5fd-8920-40f7-b86f-aab6cbd3cbdf.jpeg',
          reviewStatusType: ReviewStatus.HIDDEN,
          storageType: STORAGE_TYPE.냉동,
          status: STATUS.COMPLETED,
          isGiveawayProduct: false,
          invoice: null,
        },
      ],
      isSelfCancelable: false,
      invoices: [],
    },
    {
      orderNos: [1713932721001],
      deliveryPolicy: '판매자배송' as DeliveryPolicy,
      partnerName: '유아월드2222',
      deliveryMessage: '',
      orderStatus: ORDER_STATUS.배송완료,
      deliveryCompletedImageUrl: null,
      dealProducts: [
        {
          dealProductNo: 1000309995,
          dealProductName: '3P - 택배 (S)',
          contentsProductNo: 1000309996,
          contentsProductName: '3P - 택배',
          quantity: 1,
          displayPrice: 100,
          displayDiscountPrice: 0,
          paymentPrice: 0,
          imageUrl:
            'https://third-party-file-dev.kurly.com/cdn-cgi/image/width=120,height=156,fit=crop,quality=85/files/132f09ae-6a44-48af-abc1-8ffa3d5c3d22/a4e6e5fd-8920-40f7-b86f-aab6cbd3cbdf.jpeg',
          reviewStatusType: ReviewStatus.HIDDEN,
          storageType: STORAGE_TYPE.냉동,
          status: STATUS.COMPLETED,
          isGiveawayProduct: false,
          invoice: null,
        },
      ],
      isSelfCancelable: true,
      invoices: [],
    },
  ],
  isSelfCancelable: false,
};
export const ORDER_LIST_MOCK_DATA = {
  items: [ORDER_LIST_GROUP_ORDER_PACKING_TYPE_SINGLE, ORDER_LIST_GROUP_ORDER_PACKING_TYPE_MILTI],
  pagenation: {
    hasNext: true,
    totalPage: 5,
    currentPage: 1,
    limit: 10,
    startDate: '2024-01-11T00:00:00',
    endDate: '2024-05-15T23:59:59',
  },
};
