export enum ButtonStyle {
  BUTTON = 'BUTTON',
  IMAGE_BUTTON = 'IMAGE_BUTTON',
  BUTTON_DESCRIPTION = 'BUTTON_DESCRIPTION',
  IMAGE_BUTTON_DESCRIPTION = 'IMAGE_BUTTON_DESCRIPTION',
  BUTTON_TAG = 'BUTTON_TAG',
}
