/* eslint-disable */
export const fetchPaymentVendors = async (params: any) => [
  {
    pg_id: 'kakao-pay',
    vendor_name: '카카오페이',
    event_exists: false,
    event_description: '',
    event_title: '',
    event_descriptions: [],
    credit_card_vendor_and_installments: [],
    credit_card_point_events: [],
    instant_discount_events: [],
  },
  {
    pg_id: 'toss-payments',
    vendor_name: '신용카드',
    event_exists: false,
    event_description: '',
    event_title: '',
    event_descriptions: [],
    credit_card_vendor_and_installments: [
      {
        credit_card_vendor_code: '61',
        credit_card_vendor_name: '현대',
        installment_description: '무이자할부 유의사항 은행계열/체크/기프트/선불/법인/개인사업자 기업카드는 제외',
        installment_available: true,
        default_installment_range: [2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
        free_installment: true,
        free_interest_installment_range: [2, 3, 4, 5, 6, 7],
      },
      {
        credit_card_vendor_code: '41',
        credit_card_vendor_name: '신한',
        installment_description: '무이자할부 유의사항 은행계열/체크/기프트/선불/법인/개인사업자 기업카드는 제외',
        installment_available: true,
        default_installment_range: [2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
        free_installment: true,
        free_interest_installment_range: [2, 3, 4, 5, 6, 7],
      },
      {
        credit_card_vendor_code: '31',
        credit_card_vendor_name: '비씨(페이북)',
        installment_description: '무이자할부 유의사항 은행계열/체크/기프트/선불/법인카드는 제외',
        installment_available: true,
        default_installment_range: [2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
        free_installment: true,
        free_interest_installment_range: [2, 3, 4, 5, 6],
      },
      {
        credit_card_vendor_code: '11',
        credit_card_vendor_name: 'KB국민',
        installment_description: '무이자할부 유의사항 은행계열/체크/기프트/선불/법인/개인사업자 기업카드는 제외',
        installment_available: true,
        default_installment_range: [2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
        free_installment: true,
        free_interest_installment_range: [2, 3, 4, 5, 6],
      },
      {
        credit_card_vendor_code: '51',
        credit_card_vendor_name: '삼성',
        installment_description: '무이자할부 유의사항 은행계열/체크/기프트/선불/법인/개인사업자 기업카드는 제외',
        installment_available: true,
        default_installment_range: [2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
        free_installment: true,
        free_interest_installment_range: [2, 3, 4, 5, 6],
      },
      {
        credit_card_vendor_code: '71',
        credit_card_vendor_name: '롯데',
        installment_description: '무이자할부 유의사항 은행계열/체크/기프트/선불/법인카드는 제외',
        installment_available: true,
        default_installment_range: [2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
        free_installment: true,
        free_interest_installment_range: [2, 3, 4],
      },
      {
        credit_card_vendor_code: '21',
        credit_card_vendor_name: '하나(외환)',
        installment_description: '무이자할부 유의사항 은행계열/체크/기프트/선불/법인/개인사업자 기업카드는 제외',
        installment_available: true,
        default_installment_range: [2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
        free_installment: true,
        free_interest_installment_range: [2, 3, 4, 5, 6, 7, 8],
      },
      {
        credit_card_vendor_code: '91',
        credit_card_vendor_name: 'NH채움',
        installment_description: '무이자할부 유의사항 은행계열/체크/기프트/선불/법인/개인사업자 기업카드는 제외',
        installment_available: true,
        default_installment_range: [2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
        free_installment: true,
        free_interest_installment_range: [2, 3, 4, 5, 6],
      },
      {
        credit_card_vendor_code: '33',
        credit_card_vendor_name: '우리',
        installment_description: '무이자할부 유의사항 은행계열/체크/기프트/선불/법인카드는 제외',
        installment_available: true,
        default_installment_range: [2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
        free_installment: true,
        free_interest_installment_range: [2, 3, 4, 5, 6, 7],
      },
      {
        credit_card_vendor_code: '34',
        credit_card_vendor_name: '수협',
        installment_description: '무이자할부 유의사항 은행계열/체크/기프트/선불/법인카드는 제외',
        installment_available: true,
        default_installment_range: [2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
        free_installment: false,
        free_interest_installment_range: [],
      },
      {
        credit_card_vendor_code: '36',
        credit_card_vendor_name: '씨티',
        installment_description: '무이자할부 유의사항 은행계열/체크/기프트/선불/법인카드는 제외',
        installment_available: true,
        default_installment_range: [2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
        free_installment: true,
        free_interest_installment_range: [2, 3, 4, 5, 6],
      },
      {
        credit_card_vendor_code: '46',
        credit_card_vendor_name: '광주',
        installment_description: '무이자할부 유의사항 은행계열/체크/기프트/선불/법인카드는 제외',
        installment_available: true,
        default_installment_range: [2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
        free_installment: true,
        free_interest_installment_range: [2, 3, 4, 5],
      },
      {
        credit_card_vendor_code: '35',
        credit_card_vendor_name: '전북',
        installment_description: '무이자할부 유의사항 은행계열/체크/기프트/선불/법인카드는 제외',
        installment_available: true,
        default_installment_range: [2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
        free_installment: true,
        free_interest_installment_range: [2, 3, 4, 5],
      },
      {
        credit_card_vendor_code: '42',
        credit_card_vendor_name: '제주',
        installment_description: '무이자할부 유의사항 은행계열/체크/기프트/선불/법인카드는 제외',
        installment_available: true,
        default_installment_range: [2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
        free_installment: false,
        free_interest_installment_range: [],
      },
      {
        credit_card_vendor_code: '62',
        credit_card_vendor_name: '신협체크',
        installment_description: '무이자할부 유의사항 은행계열/체크/기프트/선불/법인카드는 제외',
        installment_available: true,
        default_installment_range: [2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
        free_installment: false,
        free_interest_installment_range: [],
      },
      {
        credit_card_vendor_code: '38',
        credit_card_vendor_name: 'MG새마을체크',
        installment_description: '무이자할부 유의사항 은행계열/체크/기프트/선불/법인카드는 제외',
        installment_available: true,
        default_installment_range: [2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
        free_installment: false,
        free_interest_installment_range: [],
      },
      {
        credit_card_vendor_code: '39',
        credit_card_vendor_name: '저축은행체크',
        installment_description: '무이자할부 유의사항 은행계열/체크/기프트/선불/법인카드는 제외',
        installment_available: true,
        default_installment_range: [2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
        free_installment: false,
        free_interest_installment_range: [],
      },
      {
        credit_card_vendor_code: '37',
        credit_card_vendor_name: '우체국카드',
        installment_description: '무이자할부 유의사항 은행계열/체크/기프트/선불/법인카드는 제외',
        installment_available: true,
        default_installment_range: [2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
        free_installment: false,
        free_interest_installment_range: [],
      },
      {
        credit_card_vendor_code: '30',
        credit_card_vendor_name: 'KDB산업은행',
        installment_description: '무이자할부 유의사항 은행계열/체크/기프트/선불/법인카드는 제외',
        installment_available: true,
        default_installment_range: [2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
        free_installment: false,
        free_interest_installment_range: [],
      },
      {
        credit_card_vendor_code: '15',
        credit_card_vendor_name: '카카오뱅크',
        installment_description: '무이자할부 유의사항 은행계열/체크/기프트/선불/법인카드는 제외',
        installment_available: true,
        default_installment_range: [2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
        free_installment: false,
        free_interest_installment_range: [],
      },
    ],
    credit_card_point_events: [],
    instant_discount_events: [],
  },
  {
    pg_id: 'toss',
    vendor_name: '토스',
    event_exists: false,
    event_description: '',
    event_title: '',
    event_descriptions: [],
    credit_card_vendor_and_installments: [],
    credit_card_point_events: [],
    instant_discount_events: [],
  },
  {
    pg_id: 'naver-pay',
    vendor_name: '네이버페이',
    event_exists: false,
    event_description: '',
    event_title: '',
    event_descriptions: [],
    credit_card_vendor_and_installments: [],
    credit_card_point_events: [],
    instant_discount_events: [],
  },
  {
    pg_id: 'payco',
    vendor_name: '페이코',
    event_exists: false,
    event_description: '',
    event_title: '페이코 충전포인트로 결제할 때마다 최대 5% 적립',
    event_descriptions: [
      '07/01 0시 ~ 08/31 24시, 기본 2% + 추가 3% 페이코 포인트 적립 (건당 최대 1, 000원)',
      '페이코로 15, 000원 이상 구매 시 페이코 앱 내 1천원 쿠폰 적용',
      '*페이코 앱 내 쿠폰영역에서 마켓컬리 쿠폰 다운로드, 결제 시 페이코 앱 내 적용',
    ],
    credit_card_vendor_and_installments: [],
    credit_card_point_events: [],
    instant_discount_events: [],
  },
];

export const fetchPreviousVendor = jest.fn().mockResolvedValue({
  creditCardVendorCode: '',
  vendorCode: 'naver-pay',
});
