import { PathKey } from '../../constant/paths';

const SSR_PAGE_LIST = [
  PathKey.GOODS_DETAIL,
  PathKey.MOBILE_GOODS_DETAIL,
  PathKey.GAMES_MY_KURLY_FARM,
  PathKey.MOBILE_GAMES_MY_KURLY_FARM,
  PathKey.SEARCH,
  PathKey.MOBILE_SEARCH,
];

const SITE_COLOR_PAGE_LIST = [
  PathKey.MAIN,
  PathKey.MAIN_BEAUTY,
  PathKey.COLLECTION_GROUPS_MARKET_NEWPRODUCT,
  PathKey.COLLECTION_GROUPS_MARKET_BEST,
  PathKey.COLLECTION_GROUPS_MARKET_SALES_GROUP,
  PathKey.MARKET_BENEFIT,
  PathKey.COLLECTION_GROUPS_BEAUTY_NEWPRODUCT,
  PathKey.COLLECTION_GROUPS_BEAUTY_BEST,
  PathKey.BEAUTY_BENEFIT,
  PathKey.BEAUTY_EVENT,
  PathKey.CATEGORY,
  PathKey.MOBILE_MYPAGE,
  PathKey.SEARCH,
];

export { SSR_PAGE_LIST, SITE_COLOR_PAGE_LIST };
