/**
 * 일반 주문 형태
 *
 * DEFAULT 장바구니 담기 가능 상품
 * SINGLE_DIRECT_ORDER 바로구매상품(싱글딜)
 * MULTIPLE_DIRECT_ORDER 바로구매상품(멀티딜)
 */
export const CART_NORMAL_ORDER_TYPE_POLICY_IN_CONTENTS = {
  DEFAULT: 'DEFAULT',
  SINGLE_DIRECT_ORDER: 'SINGLE_DIRECT_ORDER',
  MULTIPLE_DIRECT_ORDER: 'MULTIPLE_DIRECT_ORDER',
} as const;

export type CartNormalOrderTypePolicyInContents =
  typeof CART_NORMAL_ORDER_TYPE_POLICY_IN_CONTENTS[keyof typeof CART_NORMAL_ORDER_TYPE_POLICY_IN_CONTENTS];
