export enum BusinessType {
  KURLY_NON_DELIVERY = 'KURLY_NON_DELIVERY',
  KURLY_FULFILLMENT = 'KURLY_FULFILLMENT',
  KURLY_MANUAL_PROCESSING = 'KURLY_MANUAL_PROCESSING',
  PARTNER_NON_DELIVERY = 'PARTNER_NON_DELIVERY',
  PARTNER_FULFILLMENT = 'PARTNER_FULFILLMENT',
  PARTNER_KURLY_CONSIGNMENT = 'PARTNER_KURLY_CONSIGNMENT',
  PARTNER_MANUAL_PROCESSING = 'PARTNER_MANUAL_PROCESSING',
}
