const CHECKOUT_CALLBACK_FUNCTION_NAMES = {
  plccCreate: 'PLCC_CREATE_CALLBACK',
  checkoutRefresh: 'ORDER_REFRESH_CALLBACK',
  checkoutMembershipRefresh: 'MEMBERSHIP_REFRESH_CALLBACK',
};

export const CALLBACK_FUNCTION_NAMES = {
  ...CHECKOUT_CALLBACK_FUNCTION_NAMES,
};
