import { MEMBERS_BANNER, MembersBannerType } from '../constants/kurly-members-banner';
import {
  MO_ORDER_COUPON_LIST_MEMBERS_BANNER,
  MO_ORDER_COUPON_MEMBERS_BANNER,
  MO_ORDER_KURLY_PAY_MEMBERS_BANNER,
  MO_ORDER_TOTAL_PRICE_MEMBERS_BANNER,
  PC_ORDER_COUPON_LIST_MEMBERS_BANNER,
  PC_ORDER_COUPON_MEMBERS_BANNER,
  PC_ORDER_KURLY_PAY_MEMBERS_BANNER,
  PC_ORDER_TOTAL_PRICE_MEMBERS_BANNER,
} from '../constants/membersBannerQueryKeys';

export const getQueryKey = (bannerType: MembersBannerType) => {
  switch (bannerType) {
    case MEMBERS_BANNER.MO_COUPON: {
      return MO_ORDER_COUPON_MEMBERS_BANNER;
    }
    case MEMBERS_BANNER.MO_COUPON_LIST: {
      return MO_ORDER_COUPON_LIST_MEMBERS_BANNER;
    }
    case MEMBERS_BANNER.MO_TOTAL_PRICE: {
      return MO_ORDER_TOTAL_PRICE_MEMBERS_BANNER;
    }
    case MEMBERS_BANNER.MO_KURLY_PAY: {
      return MO_ORDER_KURLY_PAY_MEMBERS_BANNER;
    }
    case MEMBERS_BANNER.PC_COUPON: {
      return PC_ORDER_COUPON_MEMBERS_BANNER;
    }
    case MEMBERS_BANNER.PC_COUPON_LIST: {
      return PC_ORDER_COUPON_LIST_MEMBERS_BANNER;
    }
    case MEMBERS_BANNER.PC_TOTAL_PRICE: {
      return PC_ORDER_TOTAL_PRICE_MEMBERS_BANNER;
    }
    case MEMBERS_BANNER.PC_KURLY_PAY: {
      return PC_ORDER_KURLY_PAY_MEMBERS_BANNER;
    }
  }
};
