/* eslint-disable @typescript-eslint/no-unused-vars */

export const fetchCategory = async () => ({
  categories: [
    {
      kind: 'product_category',
      code: '780',
      name: 'SPRING FESTA',
      position: 1,
      pcIconUrl:
        'https://collection-image.kurly.com/site-category-groups/1/h7xC9i2GQ1IkCjMvdSeusB7ePGJ5x0iPMIPsK5O0.png',
      pcIconActiveUrl:
        'https://collection-image.kurly.com/site-category-groups/1/IjoDrvdfN9x3lO25EfgtmxAVsxKNWGs6xM09NdPK.png',
      mobileIconUrl: 'https://img-cf.kurly.com/shop/data/category/icon_electronic_inactive@3x.1574417979.png',
      mobileIconActiveUrl: 'https://img-cf.kurly.com/shop/data/category/icon_electronic_active@3x.1574417979.png',
      thumbnailUrl: 'https://img-cf.kurly.com/category/image/090e4182-cbcf-4c1b-bfc4-daef9ddf4a21',
      isNew: true,
      isShowAll: true,
      subCategoryGroups: [
        {
          kind: 'product_category',
          code: '780001',
          name: '+1 플러스딜',
        },
        {
          kind: 'product_category',
          code: '780019',
          name: '대표가 확인',
        },
        {
          kind: 'product_category',
          code: '780020',
          name: '캘린더형',
        },
        {
          kind: 'product_category',
          code: '780021',
          name: '옵션형',
        },
        {
          kind: 'product_category',
          code: '780022',
          name: '싱글멀티확인용',
        },
        {
          kind: 'product_category',
          code: '780023',
          name: '대카테고리테스트',
        },
      ],
    },
    {
      kind: 'product_category',
      code: '085',
      name: '가전제품',
      position: 2,
      pcIconUrl:
        'https://collection-image.kurly.com/site-category-groups/2/vF4tRY751hsFMLfzURq7sOkJDVXH0ddapXOqBIzC.png',
      pcIconActiveUrl:
        'https://collection-image.kurly.com/site-category-groups/2/QrnRm43CHT0IO6CMekeJlyArhBD4EDBl6eXmSb4Z.png',
      mobileIconUrl: 'https://img-cf.kurly.com/shop/data/category/icon_electronic_inactive@3x.1574417979.png',
      mobileIconActiveUrl: 'https://img-cf.kurly.com/shop/data/category/icon_electronic_active@3x.1574417979.png',
      thumbnailUrl: 'https://img-cf.kurly.com/category/image/090e4182-cbcf-4c1b-bfc4-daef9ddf4a21',
      isNew: false,
      isShowAll: true,
      subCategoryGroups: [
        {
          kind: 'product_category',
          code: '085002',
          name: '주방가전',
        },
        {
          kind: 'product_category',
          code: '085001',
          name: '생활가전',
        },
        {
          kind: 'product_category',
          code: '085003',
          name: '계절가전',
        },
        {
          kind: 'product_category',
          code: '085004',
          name: '디지털·PC',
        },
        {
          kind: 'product_category',
          code: '085005',
          name: '대형·설치가전',
        },
        {
          kind: 'product_category',
          code: '085006',
          name: '옵션형',
        },
        {
          kind: 'product_category',
          code: '085007',
          name: '캘린더형',
        },
        {
          kind: 'product_category',
          code: '085008',
          name: '멀티딜 대표가확인',
        },
        {
          kind: 'product_category',
          code: '085009',
          name: '싱글멀티확인용',
        },
      ],
    },
    {
      kind: 'product_category',
      code: '909',
      name: '수산·해산·건어물',
      position: 3,
      pcIconUrl:
        'https://collection-image.kurly.com/site-category-groups/3/2QyvjldT7VfyNAzL4drv0KqqN2ZVkbKmOoTXUTsD.png',
      pcIconActiveUrl:
        'https://collection-image.kurly.com/site-category-groups/3/bXePDecOE0tCuhBAWHjByurtpS0X9LnY5MRzRWfk.png',
      mobileIconUrl: 'https://img-cf.kurly.com/shop/data/category/icon_electronic_inactive@3x.1574417979.png',
      mobileIconActiveUrl: 'https://img-cf.kurly.com/shop/data/category/icon_electronic_active@3x.1574417979.png',
      thumbnailUrl: 'https://img-cf.kurly.com/category/image/090e4182-cbcf-4c1b-bfc4-daef9ddf4a21',
      isNew: false,
      isShowAll: true,
      subCategoryGroups: [
        {
          kind: 'product_category',
          code: '909007',
          name: '수산가공품',
        },
      ],
    },
    {
      kind: 'product_category',
      code: '908',
      name: '과일·견과·쌀',
      position: 4,
      pcIconUrl:
        'https://collection-image.kurly.com/site-category-groups/4/0hrAEbIFxAnRA5bAe5VLthZPy2DuuNJ2yUEGmmvu.png',
      pcIconActiveUrl:
        'https://collection-image.kurly.com/site-category-groups/4/8Qe2XRAghHcz4MeEOWxmQt4dVbtW7wmVRWQhE6qY.png',
      mobileIconUrl: 'https://img-cf.kurly.com/shop/data/category/icon_electronic_inactive@3x.1574417979.png',
      mobileIconActiveUrl: 'https://img-cf.kurly.com/shop/data/category/icon_electronic_active@3x.1574417979.png',
      thumbnailUrl: 'https://img-cf.kurly.com/category/image/090e4182-cbcf-4c1b-bfc4-daef9ddf4a21',
      isNew: false,
      isShowAll: true,
      subCategoryGroups: [
        {
          kind: 'product_category',
          code: '908008',
          name: '친환경',
        },
        {
          kind: 'product_category',
          code: '908006',
          name: '제철과일',
        },
        {
          kind: 'product_category',
          code: '908001',
          name: '국산과일',
        },
        {
          kind: 'product_category',
          code: '908002',
          name: '수입과일',
        },
        {
          kind: 'product_category',
          code: '908007',
          name: '간편과일',
        },
        {
          kind: 'product_category',
          code: '908003',
          name: '냉동·건과일',
        },
        {
          kind: 'product_category',
          code: '908004',
          name: '견과류',
        },
        {
          kind: 'product_category',
          code: '908005',
          name: '쌀·잡곡',
        },
        {
          kind: 'product_category',
          code: '908009',
          name: '채소',
        },
      ],
    },
    {
      kind: 'product_category',
      code: '910',
      name: '정육·계란',
      position: 5,
      pcIconUrl:
        'https://collection-image.kurly.com/site-category-groups/5/IrGGHty8iMhl3o4B09uRboPHEnP2Nw07dQjKftBC.png',
      pcIconActiveUrl:
        'https://collection-image.kurly.com/site-category-groups/5/jXjtYcioFUAxq5R1EtOPkzuooyT6eqD2ER27BlfY.png',
      mobileIconUrl: 'https://img-cf.kurly.com/shop/data/category/icon_electronic_inactive@3x.1574417979.png',
      mobileIconActiveUrl: 'https://img-cf.kurly.com/shop/data/category/icon_electronic_active@3x.1574417979.png',
      thumbnailUrl: 'https://img-cf.kurly.com/category/image/090e4182-cbcf-4c1b-bfc4-daef9ddf4a21',
      isNew: false,
      isShowAll: true,
      subCategoryGroups: [
        {
          kind: 'product_category',
          code: '910001',
          name: '국내산 소고기',
        },
        {
          kind: 'product_category',
          code: '910007',
          name: '수입산 소고기',
        },
        {
          kind: 'product_category',
          code: '910002',
          name: '돼지고기',
        },
        {
          kind: 'product_category',
          code: '910005',
          name: '계란류',
        },
        {
          kind: 'product_category',
          code: '910004',
          name: '닭·오리고기',
        },
        {
          kind: 'product_category',
          code: '910003',
          name: '양념육·돈까스',
        },
        {
          kind: 'product_category',
          code: '910006',
          name: '양고기',
        },
        {
          kind: 'product_category',
          code: '910008',
          name: '2차 확인 테스트용',
        },
      ],
    },
    {
      kind: 'product_category',
      code: '911',
      name: '국·반찬·메인요리',
      position: 6,
      pcIconUrl:
        'https://collection-image.kurly.com/site-category-groups/6/knz8h0AdTSS31q6EzUTdnY0tJTf1g9dyTZ4NdiWK.png',
      pcIconActiveUrl:
        'https://collection-image.kurly.com/site-category-groups/6/rHOLfiBcUA7OGVNAXFItxWKSfNvnQRSkdoT8YzU5.png',
      mobileIconUrl: 'https://img-cf.kurly.com/shop/data/category/icon_electronic_inactive@3x.1574417979.png',
      mobileIconActiveUrl: 'https://img-cf.kurly.com/shop/data/category/icon_electronic_active@3x.1574417979.png',
      thumbnailUrl: 'https://img-cf.kurly.com/category/image/090e4182-cbcf-4c1b-bfc4-daef9ddf4a21',
      isNew: false,
      isShowAll: true,
      subCategoryGroups: [
        {
          kind: 'product_category',
          code: '911001',
          name: '국·탕·찌개',
        },
        {
          kind: 'product_category',
          code: '911006',
          name: '밀키트·메인요리',
        },
        {
          kind: 'product_category',
          code: '911002',
          name: '밑반찬',
        },
        {
          kind: 'product_category',
          code: '911003',
          name: '김치·젓갈·장류',
        },
        {
          kind: 'product_category',
          code: '911005',
          name: '두부·어묵·부침개',
        },
        {
          kind: 'product_category',
          code: '911004',
          name: '베이컨·햄·통조림',
        },
      ],
    },
    {
      kind: 'product_category',
      code: '912',
      name: '샐러드·간편식',
      position: 7,
      pcIconUrl:
        'https://collection-image.kurly.com/site-category-groups/7/HGq2XBmGgjeaSEFxlM1m3ntT8HqtXRosCgEG92va.png',
      pcIconActiveUrl:
        'https://collection-image.kurly.com/site-category-groups/7/RKODioFsO0RDStStsXEsZkQSIHh9YIJBCCcVdwrD.png',
      mobileIconUrl: 'https://img-cf.kurly.com/shop/data/category/icon_electronic_inactive@3x.1574417979.png',
      mobileIconActiveUrl: 'https://img-cf.kurly.com/shop/data/category/icon_electronic_active@3x.1574417979.png',
      thumbnailUrl: 'https://img-cf.kurly.com/category/image/090e4182-cbcf-4c1b-bfc4-daef9ddf4a21',
      isNew: false,
      isShowAll: true,
      subCategoryGroups: [
        {
          kind: 'product_category',
          code: '912001',
          name: '샐러드·닭가슴살',
        },
        {
          kind: 'product_category',
          code: '912003',
          name: '도시락·밥류',
        },
        {
          kind: 'product_category',
          code: '912004',
          name: '파스타·면류',
        },
        {
          kind: 'product_category',
          code: '912005',
          name: '떡볶이·튀김·순대',
        },
        {
          kind: 'product_category',
          code: '912008',
          name: '피자·핫도그·만두',
        },
        {
          kind: 'product_category',
          code: '912007',
          name: '폭립·떡갈비·안주',
        },
        {
          kind: 'product_category',
          code: '912006',
          name: '죽·스프·카레',
        },
        {
          kind: 'product_category',
          code: '912002',
          name: '선식·시리얼',
        },
      ],
    },
    {
      kind: 'product_category',
      code: '913',
      name: '면·양념·오일',
      position: 8,
      pcIconUrl:
        'https://collection-image.kurly.com/site-category-groups/8/UJKwBcM0XaStZAOOa9FzPsgKY6GqqSOn2mggA6PI.png',
      pcIconActiveUrl:
        'https://collection-image.kurly.com/site-category-groups/8/aZ8tmfvZQ3VrAbzUu27HSHJ0U1A1iiRCEbRXXHjh.png',
      mobileIconUrl: 'https://img-cf.kurly.com/shop/data/category/icon_electronic_inactive@3x.1574417979.png',
      mobileIconActiveUrl: 'https://img-cf.kurly.com/shop/data/category/icon_electronic_active@3x.1574417979.png',
      thumbnailUrl: 'https://img-cf.kurly.com/category/image/090e4182-cbcf-4c1b-bfc4-daef9ddf4a21',
      isNew: false,
      isShowAll: true,
      subCategoryGroups: [
        {
          kind: 'product_category',
          code: '913001',
          name: '파스타·면류',
        },
        {
          kind: 'product_category',
          code: '913007',
          name: '식초·소스·드레싱',
        },
        {
          kind: 'product_category',
          code: '913003',
          name: '양념·액젓·장류',
        },
        {
          kind: 'product_category',
          code: '913006',
          name: '식용유·참기름·오일',
        },
        {
          kind: 'product_category',
          code: '913008',
          name: '소금·설탕·향신료',
        },
        {
          kind: 'product_category',
          code: '913002',
          name: '밀가루·가루·믹스',
        },
      ],
    },
    {
      kind: 'product_category',
      code: '914',
      name: '생수·음료·우유·커피',
      position: 9,
      pcIconUrl:
        'https://collection-image.kurly.com/site-category-groups/9/T4XwADe3nJHanuC0mBoAH0YT3kJIniSCZ7Hbsg9n.png',
      pcIconActiveUrl:
        'https://collection-image.kurly.com/site-category-groups/9/tus0KacLvzRMvrh98zydNGiSwTUSrRR33nKzOYx5.png',
      mobileIconUrl: 'https://img-cf.kurly.com/shop/data/category/icon_electronic_inactive@3x.1574417979.png',
      mobileIconActiveUrl: 'https://img-cf.kurly.com/shop/data/category/icon_electronic_active@3x.1574417979.png',
      thumbnailUrl: 'https://img-cf.kurly.com/category/image/090e4182-cbcf-4c1b-bfc4-daef9ddf4a21',
      isNew: false,
      isShowAll: true,
      subCategoryGroups: [
        {
          kind: 'product_category',
          code: '914001',
          name: '생수·탄산수',
        },
        {
          kind: 'product_category',
          code: '914002',
          name: '음료·주스',
        },
        {
          kind: 'product_category',
          code: '914003',
          name: '우유·두유·요거트',
        },
        {
          kind: 'product_category',
          code: '914004',
          name: '커피',
        },
        {
          kind: 'product_category',
          code: '914005',
          name: '차',
        },
      ],
    },
    {
      kind: 'product_category',
      code: '249',
      name: '간식·과자·떡',
      position: 10,
      pcIconUrl:
        'https://collection-image.kurly.com/site-category-groups/10/iYjY37OA5xyNsFCdP6kerv7JMuu8OLmiNDeFRqf0.png',
      pcIconActiveUrl:
        'https://collection-image.kurly.com/site-category-groups/10/EbKG39Az6aCCwgfWguhPo7zVjtvRPnaXIqAPczGN.png',
      mobileIconUrl: 'https://img-cf.kurly.com/shop/data/category/icon_electronic_inactive@3x.1574417979.png',
      mobileIconActiveUrl: 'https://img-cf.kurly.com/shop/data/category/icon_electronic_active@3x.1574417979.png',
      thumbnailUrl: 'https://img-cf.kurly.com/category/image/090e4182-cbcf-4c1b-bfc4-daef9ddf4a21',
      isNew: false,
      isShowAll: true,
      subCategoryGroups: [
        {
          kind: 'product_category',
          code: '249001',
          name: '과자·스낵·쿠키',
        },
        {
          kind: 'product_category',
          code: '249002',
          name: '초콜릿·젤리·캔디',
        },
        {
          kind: 'product_category',
          code: '249003',
          name: '떡·한과',
        },
        {
          kind: 'product_category',
          code: '249004',
          name: '아이스크림',
        },
      ],
    },
    {
      kind: 'product_category',
      code: '915',
      name: '베이커리·치즈·델리',
      position: 11,
      pcIconUrl:
        'https://collection-image.kurly.com/site-category-groups/11/XX0xtuAVkqGsBAcdbVsMbGzSQdLGVmdAcCyK2yWH.png',
      pcIconActiveUrl:
        'https://collection-image.kurly.com/site-category-groups/11/iu5dE5aS7mJ0fzduh6hYTixKtZqXi4yR7XkhTlr6.png',
      mobileIconUrl: 'https://img-cf.kurly.com/shop/data/category/icon_electronic_inactive@3x.1574417979.png',
      mobileIconActiveUrl: 'https://img-cf.kurly.com/shop/data/category/icon_electronic_active@3x.1574417979.png',
      thumbnailUrl: 'https://img-cf.kurly.com/category/image/090e4182-cbcf-4c1b-bfc4-daef9ddf4a21',
      isNew: false,
      isShowAll: true,
      subCategoryGroups: [
        {
          kind: 'product_category',
          code: '915001',
          name: '식빵·빵류',
        },
        {
          kind: 'product_category',
          code: '915002',
          name: '잼·버터·스프레드',
        },
        {
          kind: 'product_category',
          code: '915003',
          name: '케이크·파이·디저트',
        },
        {
          kind: 'product_category',
          code: '915004',
          name: '치즈',
        },
        {
          kind: 'product_category',
          code: '915005',
          name: '델리',
        },
        {
          kind: 'product_category',
          code: '915006',
          name: '올리브·피클',
        },
      ],
    },
    {
      kind: 'product_category',
      code: '032',
      name: '건강식품',
      position: 12,
      pcIconUrl:
        'https://collection-image.kurly.com/site-category-groups/12/qm28fWWaGciBPd3AIzSQLPufEQZUmxRlcBQoP6kU.png',
      pcIconActiveUrl:
        'https://collection-image.kurly.com/site-category-groups/12/qjPd4bWtZiihxUTf2nUmUc2P7MIxKrXEF9eiL29k.png',
      mobileIconUrl: 'https://img-cf.kurly.com/shop/data/category/icon_electronic_inactive@3x.1574417979.png',
      mobileIconActiveUrl: 'https://img-cf.kurly.com/shop/data/category/icon_electronic_active@3x.1574417979.png',
      thumbnailUrl: 'https://img-cf.kurly.com/category/image/090e4182-cbcf-4c1b-bfc4-daef9ddf4a21',
      isNew: false,
      isShowAll: true,
      subCategoryGroups: [
        {
          kind: 'product_category',
          code: '032003',
          name: '영양제',
        },
        {
          kind: 'product_category',
          code: '032004',
          name: '유산균',
        },
        {
          kind: 'product_category',
          code: '032002',
          name: '홍삼·인삼·꿀',
        },
        {
          kind: 'product_category',
          code: '032001',
          name: '건강즙·건강음료',
        },
        {
          kind: 'product_category',
          code: '032005',
          name: '건강분말·건강환',
        },
        {
          kind: 'product_category',
          code: '032008',
          name: '다이어트·이너뷰티',
        },
        {
          kind: 'product_category',
          code: '032007',
          name: '유아동',
        },
      ],
    },
    {
      kind: 'product_category',
      code: '722',
      name: '와인',
      position: 13,
      pcIconUrl:
        'https://collection-image.kurly.com/site-category-groups/13/YYwKAtijDL3uq8Ot0bhQBjFy68pJLptJhh9Zydn5.png',
      pcIconActiveUrl:
        'https://collection-image.kurly.com/site-category-groups/13/g7ngwxEIlG7i2NuXUwoBMohaAiy6odrAKhj2eFp4.png',
      mobileIconUrl: 'https://img-cf.kurly.com/shop/data/category/icon_electronic_inactive@3x.1574417979.png',
      mobileIconActiveUrl: 'https://img-cf.kurly.com/shop/data/category/icon_electronic_active@3x.1574417979.png',
      thumbnailUrl: 'https://img-cf.kurly.com/category/image/090e4182-cbcf-4c1b-bfc4-daef9ddf4a21',
      isNew: false,
      isShowAll: true,
      subCategoryGroups: [
        {
          kind: 'product_category',
          code: '722014',
          name: '레드와인',
        },
        {
          kind: 'product_category',
          code: '722012',
          name: '화이트와인',
        },
        {
          kind: 'product_category',
          code: '722013',
          name: '샴페인·스파클링',
        },
        {
          kind: 'product_category',
          code: '722015',
          name: '와인용품',
        },
        {
          kind: 'product_category',
          code: '722016',
          name: '프랑스와인',
        },
        {
          kind: 'product_category',
          code: '722017',
          name: '와인테스트',
        },
      ],
    },
    {
      kind: 'product_category',
      code: '251',
      name: '전통주',
      position: 14,
      pcIconUrl:
        'https://collection-image.kurly.com/site-category-groups/14/tXQT6wxHSuDKTGi7PkFV3agOsKUiGXDkFYkxEaER.png',
      pcIconActiveUrl:
        'https://collection-image.kurly.com/site-category-groups/14/HJWyXDj4CAYywe8awFPn5e2BtzZWOdcldegBsjhh.png',
      mobileIconUrl: 'https://img-cf.kurly.com/shop/data/category/icon_electronic_inactive@3x.1574417979.png',
      mobileIconActiveUrl: 'https://img-cf.kurly.com/shop/data/category/icon_electronic_active@3x.1574417979.png',
      thumbnailUrl: 'https://img-cf.kurly.com/category/image/090e4182-cbcf-4c1b-bfc4-daef9ddf4a21',
      isNew: false,
      isShowAll: true,
      subCategoryGroups: [
        {
          kind: 'product_category',
          code: '251001',
          name: '막걸리·약주',
        },
        {
          kind: 'product_category',
          code: '251002',
          name: '증류주·과실주',
        },
      ],
    },
    {
      kind: 'product_category',
      code: '918',
      name: '생활용품·리빙·캠핑',
      position: 15,
      pcIconUrl:
        'https://collection-image.kurly.com/site-category-groups/15/UUul7kUkvuy8dqB4LYZ4s7KKsJuTJLoXWrYPbeZn.png',
      pcIconActiveUrl:
        'https://collection-image.kurly.com/site-category-groups/15/QrMn7EE0MHtxaPuWcM0frjJcZJo3zeQzxGH9ZG2A.png',
      mobileIconUrl: 'https://img-cf.kurly.com/shop/data/category/icon_electronic_inactive@3x.1574417979.png',
      mobileIconActiveUrl: 'https://img-cf.kurly.com/shop/data/category/icon_electronic_active@3x.1574417979.png',
      thumbnailUrl: 'https://img-cf.kurly.com/category/image/090e4182-cbcf-4c1b-bfc4-daef9ddf4a21',
      isNew: false,
      isShowAll: true,
      subCategoryGroups: [
        {
          kind: 'product_category',
          code: '918007',
          name: '휴지·티슈',
        },
        {
          kind: 'product_category',
          code: '918016',
          name: '여성·위생용품',
        },
        {
          kind: 'product_category',
          code: '918008',
          name: '세제·청소용품',
        },
        {
          kind: 'product_category',
          code: '918009',
          name: '화훼·인테리어소품',
        },
        {
          kind: 'product_category',
          code: '918010',
          name: '의약외품·마스크',
        },
        {
          kind: 'product_category',
          code: '918011',
          name: '생활잡화·문구',
        },
        {
          kind: 'product_category',
          code: '918017',
          name: '캠핑용품',
        },
      ],
    },
    {
      kind: 'product_category',
      code: '233',
      name: '스킨케어·메이크업',
      position: 16,
      pcIconUrl:
        'https://collection-image.kurly.com/site-category-groups/16/xx8Ze8G1kLve2x41miB6H0brZbqstj3uP9FPRMvh.png',
      pcIconActiveUrl:
        'https://collection-image.kurly.com/site-category-groups/16/h0ho3zdo01RfUxKJzspDG8W31i1qBtCjwkgPpp5r.png',
      mobileIconUrl: 'https://img-cf.kurly.com/shop/data/category/icon_electronic_inactive@3x.1574417979.png',
      mobileIconActiveUrl: 'https://img-cf.kurly.com/shop/data/category/icon_electronic_active@3x.1574417979.png',
      thumbnailUrl: 'https://img-cf.kurly.com/category/image/090e4182-cbcf-4c1b-bfc4-daef9ddf4a21',
      isNew: false,
      isShowAll: true,
      subCategoryGroups: [
        {
          kind: 'product_category',
          code: '233001',
          name: '스킨·미스트·패드',
        },
        {
          kind: 'product_category',
          code: '233002',
          name: '에센스·앰플·로션',
        },
        {
          kind: 'product_category',
          code: '233003',
          name: '크림·오일',
        },
        {
          kind: 'product_category',
          code: '233004',
          name: '클렌징',
        },
        {
          kind: 'product_category',
          code: '233005',
          name: '마스크팩',
        },
        {
          kind: 'product_category',
          code: '233006',
          name: '선케어',
        },
        {
          kind: 'product_category',
          code: '233007',
          name: '메이크업',
        },
        {
          kind: 'product_category',
          code: '233008',
          name: '맨즈케어',
        },
        {
          kind: 'product_category',
          code: '233009',
          name: '뷰티소품·기기',
        },
      ],
    },
    {
      kind: 'product_category',
      code: '012',
      name: '헤어·바디·구강',
      position: 17,
      pcIconUrl:
        'https://collection-image.kurly.com/site-category-groups/17/NToWVZWTsqYjPQddgfyeFxDNPGATcsL6hM8aSwjg.png',
      pcIconActiveUrl:
        'https://collection-image.kurly.com/site-category-groups/17/cNHN0uQRQOuzHLGiuJZeYTaarCwnxHJE31uyxHSS.png',
      mobileIconUrl: 'https://img-cf.kurly.com/shop/data/category/icon_electronic_inactive@3x.1574417979.png',
      mobileIconActiveUrl: 'https://img-cf.kurly.com/shop/data/category/icon_electronic_active@3x.1574417979.png',
      thumbnailUrl: 'https://img-cf.kurly.com/category/image/090e4182-cbcf-4c1b-bfc4-daef9ddf4a21',
      isNew: false,
      isShowAll: true,
      subCategoryGroups: [
        {
          kind: 'product_category',
          code: '012010',
          name: '구강·면도',
        },
        {
          kind: 'product_category',
          code: '012009',
          name: '샴푸·컨디셔너',
        },
        {
          kind: 'product_category',
          code: '012014',
          name: '트리트먼트·팩',
        },
        {
          kind: 'product_category',
          code: '012015',
          name: '헤어에센스·염모',
        },
        {
          kind: 'product_category',
          code: '012008',
          name: '바디워시·스크럽',
        },
        {
          kind: 'product_category',
          code: '012016',
          name: '바디로션·크림',
        },
        {
          kind: 'product_category',
          code: '012017',
          name: '핸드·립·데오',
        },
        {
          kind: 'product_category',
          code: '012018',
          name: '향수·디퓨저',
        },
        {
          kind: 'product_category',
          code: '012012',
          name: '헤어·바디소품',
        },
      ],
    },
    {
      kind: 'product_category',
      code: '916',
      name: '주방용품 수정해봄',
      position: 18,
      pcIconUrl:
        'https://collection-image.kurly.com/site-category-groups/18/MQUB9NliV4T9kzUt6PktZNJQi89uiR3Bty0MfjaR.png',
      pcIconActiveUrl:
        'https://collection-image.kurly.com/site-category-groups/18/JIadFN31Zds5g67nnOaTYFQSwvRpL71TliBhnrNt.png',
      mobileIconUrl: 'https://img-cf.kurly.com/shop/data/category/icon_electronic_inactive@3x.1574417979.png',
      mobileIconActiveUrl: 'https://img-cf.kurly.com/shop/data/category/icon_electronic_active@3x.1574417979.png',
      thumbnailUrl: 'https://img-cf.kurly.com/category/image/090e4182-cbcf-4c1b-bfc4-daef9ddf4a21',
      isNew: false,
      isShowAll: true,
      subCategoryGroups: [
        {
          kind: 'product_category',
          code: '916006',
          name: '주방소모품·잡화',
        },
        {
          kind: 'product_category',
          code: '916007',
          name: '주방·조리도구',
        },
        {
          kind: 'product_category',
          code: '916008',
          name: '냄비·팬·솥',
        },
        {
          kind: 'product_category',
          code: '916011',
          name: '보관용기·텀블러',
        },
        {
          kind: 'product_category',
          code: '916009',
          name: '식기·테이블웨어',
        },
        {
          kind: 'product_category',
          code: '916010',
          name: '컵·잔·커피도구',
        },
      ],
    },
    {
      kind: 'product_category',
      code: '991',
      name: '반려동물',
      position: 19,
      pcIconUrl:
        'https://collection-image.kurly.com/site-category-groups/19/wNm8l004I36mzTgq0HGcBAxZ2qOQPi5viY8dFVZW.png',
      pcIconActiveUrl:
        'https://collection-image.kurly.com/site-category-groups/19/yUu7QUkcaMbJu9qB9LDso5qAjGJbwq3gOiPPnivp.png',
      mobileIconUrl: 'https://img-cf.kurly.com/shop/data/category/icon_electronic_inactive@3x.1574417979.png',
      mobileIconActiveUrl: 'https://img-cf.kurly.com/shop/data/category/icon_electronic_active@3x.1574417979.png',
      thumbnailUrl: 'https://img-cf.kurly.com/category/image/090e4182-cbcf-4c1b-bfc4-daef9ddf4a21',
      isNew: false,
      isShowAll: true,
      subCategoryGroups: [
        {
          kind: 'product_category',
          code: '991001',
          name: '강아지 간식',
        },
        {
          kind: 'product_category',
          code: '991002',
          name: '강아지 주식',
        },
        {
          kind: 'product_category',
          code: '991003',
          name: '고양이 간식',
        },
        {
          kind: 'product_category',
          code: '991004',
          name: '고양이 주식',
        },
        {
          kind: 'product_category',
          code: '991006',
          name: '반려동물 용품',
        },
        {
          kind: 'product_category',
          code: '991007',
          name: '배변·위생',
        },
        {
          kind: 'product_category',
          code: '991008',
          name: '소용량·샘플',
        },
        {
          kind: 'product_category',
          code: '991009',
          name: '반려식물은없나요',
        },
      ],
    },
    {
      kind: 'product_category',
      code: '919',
      name: '베이비·키즈·완구',
      position: 20,
      pcIconUrl:
        'https://collection-image.kurly.com/site-category-groups/20/9YVUK2RvBZo8b5ue2WuUuj6y2x6fkiEl4CdKNDrx.png',
      pcIconActiveUrl:
        'https://collection-image.kurly.com/site-category-groups/20/6gmPatPMjXMpZChbOSN7kevUZcPG2D3uyvipfpb8.png',
      mobileIconUrl: 'https://img-cf.kurly.com/shop/data/category/icon_electronic_inactive@3x.1574417979.png',
      mobileIconActiveUrl: 'https://img-cf.kurly.com/shop/data/category/icon_electronic_active@3x.1574417979.png',
      thumbnailUrl: 'https://img-cf.kurly.com/category/image/090e4182-cbcf-4c1b-bfc4-daef9ddf4a21',
      isNew: false,
      isShowAll: true,
      subCategoryGroups: [
        {
          kind: 'product_category',
          code: '919011',
          name: '분유·간편 이유식',
        },
        {
          kind: 'product_category',
          code: '919008',
          name: '이유식 재료',
        },
        {
          kind: 'product_category',
          code: '919013',
          name: '간식·음식·음료',
        },
        {
          kind: 'product_category',
          code: '919012',
          name: '건강식품',
        },
        {
          kind: 'product_category',
          code: '919009',
          name: '이유·수유용품',
        },
        {
          kind: 'product_category',
          code: '919014',
          name: '기저귀·물티슈',
        },
        {
          kind: 'product_category',
          code: '919010',
          name: '세제·위생용품',
        },
        {
          kind: 'product_category',
          code: '919015',
          name: '스킨·구강케어',
        },
        {
          kind: 'product_category',
          code: '919016',
          name: '완구·잡화류',
        },
      ],
    },
    {
      kind: 'product_category',
      code: '031',
      name: 'QA통합테스트',
      position: 21,
      pcIconUrl: '',
      pcIconActiveUrl: '',
      mobileIconUrl: 'https://img-cf.kurly.com/shop/data/category/icon_electronic_inactive@3x.1574417979.png',
      mobileIconActiveUrl: 'https://img-cf.kurly.com/shop/data/category/icon_electronic_active@3x.1574417979.png',
      thumbnailUrl: 'https://img-cf.kurly.com/category/image/090e4182-cbcf-4c1b-bfc4-daef9ddf4a21',
      isNew: false,
      isShowAll: true,
      subCategoryGroups: [
        {
          kind: 'product_category',
          code: '031008',
          name: '210',
        },
        {
          kind: 'product_category',
          code: '031012',
          name: '220',
        },
        {
          kind: 'product_category',
          code: '031010',
          name: '225',
        },
        {
          kind: 'product_category',
          code: '031009',
          name: '226',
        },
        {
          kind: 'product_category',
          code: '031013',
          name: '227',
        },
        {
          kind: 'product_category',
          code: '031007',
          name: '237',
        },
        {
          kind: 'product_category',
          code: '031011',
          name: '235',
        },
        {
          kind: 'product_category',
          code: '031002',
          name: '238',
        },
      ],
    },
  ],
  recommend: [
    {
      kind: 'product_category',
      code: '085',
      name: '가전제품',
      position: 1,
      pcIconUrl: '',
      pcIconActiveUrl: '',
      mobileIconUrl: 'https://img-cf.kurly.com/shop/data/category/icon_electronic_inactive@3x.1574417979.png',
      mobileIconActiveUrl: 'https://img-cf.kurly.com/shop/data/category/icon_electronic_active@3x.1574417979.png',
      thumbnailUrl: 'https://img-cf.kurly.com/category/image/090e4182-cbcf-4c1b-bfc4-daef9ddf4a21',
      isNew: false,
      isShowAll: true,
      subCategoryGroups: [
        {
          kind: 'product_category',
          code: '085002',
          name: '주방가전',
        },
        {
          kind: 'product_category',
          code: '085001',
          name: '생활가전',
        },
        {
          kind: 'product_category',
          code: '085003',
          name: '계절가전',
        },
        {
          kind: 'product_category',
          code: '085004',
          name: '디지털·PC',
        },
        {
          kind: 'product_category',
          code: '085005',
          name: '대형·설치가전',
        },
        {
          kind: 'product_category',
          code: '085006',
          name: '옵션형',
        },
        {
          kind: 'product_category',
          code: '085007',
          name: '캘린더형',
        },
        {
          kind: 'product_category',
          code: '085008',
          name: '멀티딜 대표가확인',
        },
        {
          kind: 'product_category',
          code: '085009',
          name: '싱글멀티확인용',
        },
      ],
    },
    {
      kind: 'product_category',
      code: '206',
      name: '여행·문화',
      position: 2,
      pcIconUrl: '',
      pcIconActiveUrl: '',
      mobileIconUrl: 'https://img-cf.kurly.com/shop/data/category/icon_electronic_inactive@3x.1574417979.png',
      mobileIconActiveUrl: 'https://img-cf.kurly.com/shop/data/category/icon_electronic_active@3x.1574417979.png',
      thumbnailUrl: 'https://img-cf.kurly.com/category/image/090e4182-cbcf-4c1b-bfc4-daef9ddf4a21',
      isNew: false,
      isShowAll: false,
      subCategoryGroups: [
        {
          kind: 'product_category',
          code: '206001',
          name: '숙박권',
        },
        {
          kind: 'product_category',
          code: '206009',
          name: '국내 숙박·항공·전시',
        },
        {
          kind: 'product_category',
          code: '206010',
          name: '여행 필수템',
        },
        {
          kind: 'product_category',
          code: '206011',
          name: '우리집을 호텔처럼',
        },
        {
          kind: 'product_category',
          code: '206012',
          name: '지난상품보기',
        },
      ],
    },
    {
      kind: 'product_category',
      code: '724',
      name: '홈캉스',
      position: 3,
      pcIconUrl: '',
      pcIconActiveUrl: '',
      mobileIconUrl: 'https://img-cf.kurly.com/shop/data/category/icon_electronic_inactive@3x.1574417979.png',
      mobileIconActiveUrl: 'https://img-cf.kurly.com/shop/data/category/icon_electronic_active@3x.1574417979.png',
      thumbnailUrl: 'https://img-cf.kurly.com/category/image/090e4182-cbcf-4c1b-bfc4-daef9ddf4a21',
      isNew: false,
      isShowAll: true,
      subCategoryGroups: [
        {
          kind: 'product_category',
          code: '724001',
          name: '브런치',
        },
        {
          kind: 'product_category',
          code: '724002',
          name: '홈카페',
        },
        {
          kind: 'product_category',
          code: '724006',
          name: '홈스토랑',
        },
        {
          kind: 'product_category',
          code: '724003',
          name: '홈술',
        },
        {
          kind: 'product_category',
          code: '724004',
          name: '홈스파',
        },
        {
          kind: 'product_category',
          code: '724005',
          name: '홈테인먼트',
        },
      ],
    },
    {
      kind: 'product_category',
      code: '007',
      name: '식단관리',
      position: 4,
      pcIconUrl: '',
      pcIconActiveUrl: '',
      mobileIconUrl: 'https://img-cf.kurly.com/shop/data/category/icon_electronic_inactive@3x.1574417979.png',
      mobileIconActiveUrl: 'https://img-cf.kurly.com/shop/data/category/icon_electronic_active@3x.1574417979.png',
      thumbnailUrl: 'https://img-cf.kurly.com/category/image/090e4182-cbcf-4c1b-bfc4-daef9ddf4a21',
      isNew: false,
      isShowAll: false,
      subCategoryGroups: [
        {
          kind: 'product_category',
          code: '007001',
          name: '샐러드',
        },
        {
          kind: 'product_category',
          code: '007008',
          name: '닭가슴살·달걀',
        },
        {
          kind: 'product_category',
          code: '007002',
          name: '도시락·간편식',
        },
        {
          kind: 'product_category',
          code: '007009',
          name: '간식·선식·시리얼',
        },
        {
          kind: 'product_category',
          code: '007006',
          name: '클렌즈 주스',
        },
        {
          kind: 'product_category',
          code: '007010',
          name: '프로틴·보조제',
        },
      ],
    },
    {
      kind: 'product_category',
      code: '001',
      name: '간편한 아침식사',
      position: 5,
      pcIconUrl: '',
      pcIconActiveUrl: '',
      mobileIconUrl: 'https://img-cf.kurly.com/shop/data/category/icon_electronic_inactive@3x.1574417979.png',
      mobileIconActiveUrl: 'https://img-cf.kurly.com/shop/data/category/icon_electronic_active@3x.1574417979.png',
      thumbnailUrl: 'https://img-cf.kurly.com/category/image/090e4182-cbcf-4c1b-bfc4-daef9ddf4a21',
      isNew: false,
      isShowAll: false,
      subCategoryGroups: [
        {
          kind: 'product_category',
          code: '001001',
          name: '베이커리·델리',
        },
        {
          kind: 'product_category',
          code: '001005',
          name: '우유·커피·주스',
        },
        {
          kind: 'product_category',
          code: '001002',
          name: '과일',
        },
        {
          kind: 'product_category',
          code: '001003',
          name: '샐러드·간편식·스프',
        },
        {
          kind: 'product_category',
          code: '001004',
          name: '선식·시리얼·그래놀라',
        },
      ],
    },
    {
      kind: 'product_category',
      code: '948',
      name: '재구매 BEST',
      position: 6,
      pcIconUrl: '',
      pcIconActiveUrl: '',
      mobileIconUrl: 'https://img-cf.kurly.com/shop/data/category/icon_electronic_inactive@3x.1574417979.png',
      mobileIconActiveUrl: 'https://img-cf.kurly.com/shop/data/category/icon_electronic_active@3x.1574417979.png',
      thumbnailUrl: 'https://img-cf.kurly.com/category/image/090e4182-cbcf-4c1b-bfc4-daef9ddf4a21',
      isNew: false,
      isShowAll: false,
      subCategoryGroups: [
        {
          kind: 'product_category',
          code: '948001',
          name: '신선식품',
        },
        {
          kind: 'product_category',
          code: '948002',
          name: '가공식품',
        },
        {
          kind: 'product_category',
          code: '948003',
          name: '반찬·간편식',
        },
        {
          kind: 'product_category',
          code: '948004',
          name: '리빙·뷰티·펫',
        },
      ],
    },
    {
      kind: 'product_category',
      code: '183',
      name: '3천원의 행복',
      position: 7,
      pcIconUrl: '',
      pcIconActiveUrl: '',
      mobileIconUrl: 'https://img-cf.kurly.com/shop/data/category/icon_electronic_inactive@3x.1574417979.png',
      mobileIconActiveUrl: 'https://img-cf.kurly.com/shop/data/category/icon_electronic_active@3x.1574417979.png',
      thumbnailUrl: 'https://img-cf.kurly.com/category/image/090e4182-cbcf-4c1b-bfc4-daef9ddf4a21',
      isNew: false,
      isShowAll: true,
      subCategoryGroups: [
        {
          kind: 'product_category',
          code: '183001',
          name: '1천원 미만',
        },
        {
          kind: 'product_category',
          code: '183002',
          name: '2천원 미만',
        },
        {
          kind: 'product_category',
          code: '183003',
          name: '3천원 미만',
        },
      ],
    },
    {
      kind: 'product_category',
      code: '315',
      name: '컬리마트',
      position: 8,
      pcIconUrl: '',
      pcIconActiveUrl: '',
      mobileIconUrl: 'https://img-cf.kurly.com/shop/data/category/icon_electronic_inactive@3x.1574417979.png',
      mobileIconActiveUrl: 'https://img-cf.kurly.com/shop/data/category/icon_electronic_active@3x.1574417979.png',
      thumbnailUrl: 'https://img-cf.kurly.com/category/image/090e4182-cbcf-4c1b-bfc4-daef9ddf4a21',
      isNew: false,
      isShowAll: true,
      subCategoryGroups: [
        {
          kind: 'product_category',
          code: '315008',
          name: '라면·간편식',
        },
        {
          kind: 'product_category',
          code: '315009',
          name: '김치·반찬',
        },
        {
          kind: 'product_category',
          code: '315010',
          name: '간식·과자·시리얼',
        },
        {
          kind: 'product_category',
          code: '315014',
          name: '유제품·아이스크림',
        },
        {
          kind: 'product_category',
          code: '315006',
          name: '생수·음료·커피',
        },
        {
          kind: 'product_category',
          code: '315005',
          name: '장류·양념·오일',
        },
        {
          kind: 'product_category',
          code: '315012',
          name: '제지·생리대·기저귀',
        },
        {
          kind: 'product_category',
          code: '315013',
          name: '헤어·바디·구강',
        },
        {
          kind: 'product_category',
          code: '315007',
          name: '생활·주방용품',
        },
      ],
    },
    {
      kind: 'product_category',
      code: '068',
      name: '대용량 상품',
      position: 9,
      pcIconUrl: '',
      pcIconActiveUrl: '',
      mobileIconUrl: 'https://img-cf.kurly.com/shop/data/category/icon_electronic_inactive@3x.1574417979.png',
      mobileIconActiveUrl: 'https://img-cf.kurly.com/shop/data/category/icon_electronic_active@3x.1574417979.png',
      thumbnailUrl: 'https://img-cf.kurly.com/category/image/090e4182-cbcf-4c1b-bfc4-daef9ddf4a21',
      isNew: false,
      isShowAll: true,
      subCategoryGroups: [],
    },
    {
      kind: 'product_category',
      code: '228',
      name: '캠핑',
      position: 10,
      pcIconUrl: '',
      pcIconActiveUrl: '',
      mobileIconUrl: 'https://img-cf.kurly.com/shop/data/category/icon_electronic_inactive@3x.1574417979.png',
      mobileIconActiveUrl: 'https://img-cf.kurly.com/shop/data/category/icon_electronic_active@3x.1574417979.png',
      thumbnailUrl: 'https://img-cf.kurly.com/category/image/090e4182-cbcf-4c1b-bfc4-daef9ddf4a21',
      isNew: false,
      isShowAll: false,
      subCategoryGroups: [
        {
          kind: 'product_category',
          code: '228006',
          name: '캠핑용품',
        },
        {
          kind: 'product_category',
          code: '228001',
          name: '바베큐',
        },
        {
          kind: 'product_category',
          code: '228002',
          name: '채소·과일',
        },
        {
          kind: 'product_category',
          code: '228003',
          name: '간편식·반찬',
        },
        {
          kind: 'product_category',
          code: '228004',
          name: '양념·소스',
        },
        {
          kind: 'product_category',
          code: '228005',
          name: '간식·음료',
        },
      ],
    },
    {
      kind: 'product_category',
      code: '955',
      name: '1인 가구',
      position: 11,
      pcIconUrl: '',
      pcIconActiveUrl: '',
      mobileIconUrl: 'https://img-cf.kurly.com/shop/data/category/icon_electronic_inactive@3x.1574417979.png',
      mobileIconActiveUrl: 'https://img-cf.kurly.com/shop/data/category/icon_electronic_active@3x.1574417979.png',
      thumbnailUrl: 'https://img-cf.kurly.com/category/image/090e4182-cbcf-4c1b-bfc4-daef9ddf4a21',
      isNew: false,
      isShowAll: true,
      subCategoryGroups: [
        {
          kind: 'product_category',
          code: '955003',
          name: '한끼채소',
        },
        {
          kind: 'product_category',
          code: '955001',
          name: '과일/쌀',
        },
        {
          kind: 'product_category',
          code: '955002',
          name: '간편식/재료',
        },
        {
          kind: 'product_category',
          code: '955004',
          name: '간식/음료',
        },
        {
          kind: 'product_category',
          code: '955005',
          name: '생활용품',
        },
        {
          kind: 'product_category',
          code: '955006',
          name: '이케아',
        },
      ],
    },
    {
      kind: 'product_category',
      code: '525',
      name: '비건',
      position: 12,
      pcIconUrl: '',
      pcIconActiveUrl: '',
      mobileIconUrl: 'https://img-cf.kurly.com/shop/data/category/icon_electronic_inactive@3x.1574417979.png',
      mobileIconActiveUrl: 'https://img-cf.kurly.com/shop/data/category/icon_electronic_active@3x.1574417979.png',
      thumbnailUrl: 'https://img-cf.kurly.com/category/image/090e4182-cbcf-4c1b-bfc4-daef9ddf4a21',
      isNew: false,
      isShowAll: true,
      subCategoryGroups: [
        {
          kind: 'product_category',
          code: '525002',
          name: '대체육·간편식',
        },
        {
          kind: 'product_category',
          code: '525008',
          name: '대체유제품·음료',
        },
        {
          kind: 'product_category',
          code: '525004',
          name: '샐러드',
        },
        {
          kind: 'product_category',
          code: '525006',
          name: '시리얼·선식',
        },
        {
          kind: 'product_category',
          code: '525001',
          name: '간식',
        },
        {
          kind: 'product_category',
          code: '525003',
          name: '베이커리',
        },
        {
          kind: 'product_category',
          code: '525007',
          name: '양념·소스',
        },
        {
          kind: 'product_category',
          code: '525005',
          name: '생활·뷰티',
        },
      ],
    },
    {
      kind: 'product_category',
      code: '990',
      name: '오프라인 맛집',
      position: 13,
      pcIconUrl: '',
      pcIconActiveUrl: '',
      mobileIconUrl: 'https://img-cf.kurly.com/shop/data/category/icon_electronic_inactive@3x.1574417979.png',
      mobileIconActiveUrl: 'https://img-cf.kurly.com/shop/data/category/icon_electronic_active@3x.1574417979.png',
      thumbnailUrl: 'https://img-cf.kurly.com/category/image/090e4182-cbcf-4c1b-bfc4-daef9ddf4a21',
      isNew: false,
      isShowAll: true,
      subCategoryGroups: [
        {
          kind: 'product_category',
          code: '990003',
          name: '양식',
        },
        {
          kind: 'product_category',
          code: '990004',
          name: '한식',
        },
        {
          kind: 'product_category',
          code: '990005',
          name: '중식',
        },
        {
          kind: 'product_category',
          code: '990006',
          name: '분식',
        },
        {
          kind: 'product_category',
          code: '990007',
          name: '아시안',
        },
        {
          kind: 'product_category',
          code: '990008',
          name: '베이커리',
        },
        {
          kind: 'product_category',
          code: '990009',
          name: '카페',
        },
      ],
    },
    {
      kind: 'product_category',
      code: '726',
      name: '컬리가 만든 상품',
      position: 14,
      pcIconUrl: '',
      pcIconActiveUrl: '',
      mobileIconUrl: 'https://img-cf.kurly.com/shop/data/category/icon_electronic_inactive@3x.1574417979.png',
      mobileIconActiveUrl: 'https://img-cf.kurly.com/shop/data/category/icon_electronic_active@3x.1574417979.png',
      thumbnailUrl: 'https://img-cf.kurly.com/category/image/090e4182-cbcf-4c1b-bfc4-daef9ddf4a21',
      isNew: false,
      isShowAll: false,
      subCategoryGroups: [
        {
          kind: 'product_category',
          code: '726003',
          name: 'Kurly`s 식품',
        },
        {
          kind: 'product_category',
          code: '726004',
          name: 'Kurly`s 생활용품',
        },
        {
          kind: 'product_category',
          code: '726002',
          name: '일반 상품',
        },
      ],
    },
    {
      kind: 'product_category',
      code: '075',
      name: 'Kurly Only',
      position: 15,
      pcIconUrl: '',
      pcIconActiveUrl: '',
      mobileIconUrl: 'https://img-cf.kurly.com/shop/data/category/icon_electronic_inactive@3x.1574417979.png',
      mobileIconActiveUrl: 'https://img-cf.kurly.com/shop/data/category/icon_electronic_active@3x.1574417979.png',
      thumbnailUrl: 'https://img-cf.kurly.com/category/image/090e4182-cbcf-4c1b-bfc4-daef9ddf4a21',
      isNew: false,
      isShowAll: true,
      subCategoryGroups: [
        {
          kind: 'product_category',
          code: '075009',
          name: '베이커리·간식',
        },
        {
          kind: 'product_category',
          code: '075004',
          name: '반찬·간편식',
        },
        {
          kind: 'product_category',
          code: '075005',
          name: '유제품·음료',
        },
        {
          kind: 'product_category',
          code: '075001',
          name: '농산',
        },
        {
          kind: 'product_category',
          code: '075002',
          name: '수산',
        },
        {
          kind: 'product_category',
          code: '075003',
          name: '정육·계란',
        },
        {
          kind: 'product_category',
          code: '075006',
          name: '가공식품',
        },
        {
          kind: 'product_category',
          code: '075007',
          name: '건강식품',
        },
        {
          kind: 'product_category',
          code: '075008',
          name: '리빙·펫',
        },
      ],
    },
    {
      kind: 'product_category',
      code: '316',
      name: 'KF365',
      position: 16,
      pcIconUrl: '',
      pcIconActiveUrl: '',
      mobileIconUrl: 'https://img-cf.kurly.com/shop/data/category/icon_electronic_inactive@3x.1574417979.png',
      mobileIconActiveUrl: 'https://img-cf.kurly.com/shop/data/category/icon_electronic_active@3x.1574417979.png',
      thumbnailUrl: 'https://img-cf.kurly.om/category/image/090e4182-cbcf-4c1b-bfc4-daef9ddf4a21',
      isNew: false,
      isShowAll: true,
      subCategoryGroups: [
        {
          kind: 'product_category',
          code: '316001',
          name: '채소·과일',
        },
        {
          kind: 'product_category',
          code: '316002',
          name: '정육·달걀',
        },
        {
          kind: 'product_category',
          code: '316003',
          name: '수산',
        },
        {
          kind: 'product_category',
          code: '316004',
          name: '리빙',
        },
        {
          kind: 'product_category',
          code: '316005',
          name: '탄산수',
        },
      ],
    },
    {
      kind: 'product_category',
      code: '127',
      name: '1% Table',
      position: 17,
      pcIconUrl: '',
      pcIconActiveUrl: '',
      mobileIconUrl: 'https://img-cf.kurly.com/shop/data/category/icon_electronic_inactive@3x.1574417979.png',
      mobileIconActiveUrl: 'https://img-cf.kurly.com/shop/data/category/icon_electronic_active@3x.1574417979.png',
      thumbnailUrl: 'https://img-cf.kurly.com/catey/image/090e4182-cbcf-4c1b-bfc4-daef9ddf4a21',
      isNew: false,
      isShowAll: true,
      subCategoryGroups: [
        {
          kind: 'product_category',
          code: '127001',
          name: '과일',
        },
        {
          kind: 'product_category',
          code: '127002',
          name: '정육',
        },
        {
          kind: 'product_category',
          code: '127003',
          name: '수산',
        },
        {
          kind: 'product_category',
          code: '127004',
          name: '커피',
        },
        {
          kind: 'product_category',
          code: '127005',
          name: '치즈·잼',
        },
      ],
    },
  ],
  categoriesMeta: {
    recommend: {
      pcIconUrl: 'https://res.kurly.com/pc/service/common/1908/ico_recommend_v2.png',
      pcIconActiveUrl: 'https://res.kurly.com/pc/service/common/1908/ico_recommend_on_v2.png',
    },
    isNew: {
      iconUrl: 'https://res.kurly.com/pc/service/common/1908/ico_new_42x42_v2.png',
    },
  },
});
