const BLOCK_KEY = ['MBMER', 'BLOCK'];
const BLOCK_REASON_KEY = [...BLOCK_KEY, 'REASON'];
const BLOCK_LOCK_NUMBER_KEY = [...BLOCK_KEY, 'LOCK_NUMBER'];

export { BLOCK_KEY, BLOCK_REASON_KEY, BLOCK_LOCK_NUMBER_KEY };
