import { z } from 'zod';
import {
  Apple,
  ArrowBottom,
  ArrowBottomSmall_2x3,
  ArrowLeft,
  ArrowLeft_1x2,
  ArrowLeftSmall,
  ArrowLeftSmall_1x2,
  ArrowRight,
  ArrowRight_1x2,
  ArrowRightSmall,
  ArrowRightSmall_1x2,
  ArrowTop,
  ArrowTopSmall_2x3,
  ArrowUp,
  Basket,
  Bell,
  Blank,
  Calendar,
  Cart_stroke_regular,
  Cart_stroke_light,
  CellIndicator,
  Close,
  CloseCircle,
  Copy_stroke,
  Copy_fill,
  Delete,
  ErrorCircle,
  ErrorCircle_red,
  ErrorTriangle,
  Filter,
  Freeze,
  Gift,
  Heart,
  InfoCircle,
  Kakao,
  Location_stroke,
  Location_fill,
  Menu,
  Minus,
  More,
  MoreInfo,
  Pause,
  Person_stroke,
  Person_fill,
  Play,
  Plus,
  QRCode,
  QuestionCircle,
  Refresh,
  Search,
  SoundOff,
  SoundOn,
  Sun,
  TextBubble_stroke_regular,
  TextBubble_stroke_light,
  TextBubble_fill,
  WaterDrop,
  WaterDrop_2x3,
  WarnCircle_red,
  CheckCircle_green,
  Photo_stroke_light,
  Photo_stroke_regular,
} from '@/internal/Icons';

const ICON_TYPE_ENUM = z.enum([
  'Apple',
  'ArrowBottom',
  'ArrowBottomSmall',
  'ArrowLeft',
  'ArrowLeftSmall',
  'ArrowRight',
  'ArrowRightSmall',
  'ArrowRightSmall',
  'ArrowTop',
  'ArrowTopSmall',
  'ArrowUp',
  'Basket',
  'Bell',
  'Blank',
  'Calendar',
  'Cart',
  'CellIndicator',
  'Close',
  'CloseCircle',
  'Copy',
  'Copy',
  'Delete',
  'ErrorCircle',
  'ErrorCircle_red',
  'ErrorTriangle',
  'Filter',
  'Freeze',
  'Gift',
  'Heart',
  'InfoCircle',
  'Kakao',
  'Location',
  'Menu',
  'Minus',
  'More',
  'MoreInfo',
  'Pause',
  'Person',
  'Play',
  'Plus',
  'QRCode',
  'QuestionCircle',
  'Refresh',
  'Search',
  'SoundOff',
  'SoundOn',
  'Sun',
  'TextBubble',
  'WaterDrop',
  'WarnCircle',
  'CheckCircle',
  'Photo',
]);

const ACTUAL_ICON_TYPE_ENUM = z.enum([
  'Apple_1x1_DEFAULT_DEFAULT',
  'ArrowBottom_1x1_DEFAULT_DEFAULT',
  'ArrowBottomSmall_2x3_DEFAULT_DEFAULT',
  'ArrowLeft_1x1_DEFAULT_DEFAULT',
  'ArrowLeft_1x2_DEFAULT_DEFAULT',
  'ArrowLeftSmall_1x1_DEFAULT_DEFAULT',
  'ArrowLeftSmall_1x2_DEFAULT_DEFAULT',
  'ArrowRight_1x1_DEFAULT_DEFAULT',
  'ArrowRight_1x2_DEFAULT_DEFAULT',
  'ArrowRightSmall_1x1_DEFAULT_DEFAULT',
  'ArrowRightSmall_1x2_DEFAULT_DEFAULT',
  'ArrowTop_1x1_DEFAULT_DEFAULT',
  'ArrowTopSmall_2x3_DEFAULT_DEFAULT',
  'ArrowUp_1x1_DEFAULT_DEFAULT',
  'Basket_1x1_DEFAULT_DEFAULT',
  'Bell_1x1_DEFAULT_DEFAULT',
  'Blank_1x1_DEFAULT_DEFAULT',
  'Calendar_1x1_DEFAULT_DEFAULT',
  'Cart_1x1_stroke_regular',
  'Cart_1x1_stroke_light',
  'CellIndicator_1x1_DEFAULT_DEFAULT',
  'Close_1x1_DEFAULT_DEFAULT',
  'CloseCircle_1x1_DEFAULT_DEFAULT',
  'Copy_1x1_stroke_DEFAULT',
  'Copy_1x1_fill_DEFAULT',
  'Delete_1x1_DEFAULT_DEFAULT',
  'ErrorCircle_1x1_DEFAULT_DEFAULT',
  'ErrorTriangle_1x1_DEFAULT_DEFAULT',
  'Filter_1x1_DEFAULT_DEFAULT',
  'Freeze_1x1_DEFAULT_DEFAULT',
  'Gift_1x1_DEFAULT_DEFAULT',
  'Heart_1x1_DEFAULT_DEFAULT',
  'InfoCircle_1x1_DEFAULT_DEFAULT',
  'Kakao_1x1_DEFAULT_DEFAULT',
  'Location_1x1_stroke_DEFAULT',
  'Location_1x1_fill_DEFAULT',
  'Menu_1x1_DEFAULT_DEFAULT',
  'Minus_1x1_DEFAULT_DEFAULT',
  'More_1x1_DEFAULT_DEFAULT',
  'MoreInfo_1x1_DEFAULT_DEFAULT',
  'Pause_1x1_DEFAULT_DEFAULT',
  'Person_1x1_stroke_DEFAULT',
  'Person_1x1_fill_DEFAULT',
  'Play_1x1_DEFAULT_DEFAULT',
  'Plus_1x1_DEFAULT_DEFAULT',
  'QRCode_1x1_DEFAULT_DEFAULT',
  'QuestionCircle_1x1_DEFAULT_DEFAULT',
  'Refresh_1x1_DEFAULT_DEFAULT',
  'Search_1x1_DEFAULT_DEFAULT',
  'SoundOff_1x1_DEFAULT_DEFAULT',
  'SoundOn_1x1_DEFAULT_DEFAULT',
  'Sun_1x1_DEFAULT_DEFAULT',
  'TextBubble_1x1_stroke_regular',
  'TextBubble_1x1_stroke_light',
  'TextBubble_1x1_fill_DEFAULT',
  'WaterDrop_1x1_DEFAULT_DEFAULT',
  'WaterDrop_2x3_DEFAULT_DEFAULT',
  'WarnCircle_1x1_DEFAULT_DEFAULT',
  'CheckCircle_1x1_DEFAULT_DEFAULT',
  'ErrorCircle_red_1x1_DEFAULT_DEFAULT',
  'Photo_1x1_stroke_regular',
  'Photo_1x1_stroke_light',
]);

const ACTUAL_ICON_MAP = new Map([
  [ACTUAL_ICON_TYPE_ENUM.enum['Apple_1x1_DEFAULT_DEFAULT'], Apple],
  [ACTUAL_ICON_TYPE_ENUM.enum['ArrowBottom_1x1_DEFAULT_DEFAULT'], ArrowBottom],
  [ACTUAL_ICON_TYPE_ENUM.enum['ArrowBottomSmall_2x3_DEFAULT_DEFAULT'], ArrowBottomSmall_2x3],
  [ACTUAL_ICON_TYPE_ENUM.enum['ArrowLeft_1x1_DEFAULT_DEFAULT'], ArrowLeft],
  [ACTUAL_ICON_TYPE_ENUM.enum['ArrowLeft_1x2_DEFAULT_DEFAULT'], ArrowLeft_1x2],
  [ACTUAL_ICON_TYPE_ENUM.enum['ArrowLeftSmall_1x1_DEFAULT_DEFAULT'], ArrowLeftSmall],
  [ACTUAL_ICON_TYPE_ENUM.enum['ArrowLeftSmall_1x2_DEFAULT_DEFAULT'], ArrowLeftSmall_1x2],
  [ACTUAL_ICON_TYPE_ENUM.enum['ArrowRight_1x1_DEFAULT_DEFAULT'], ArrowRight],
  [ACTUAL_ICON_TYPE_ENUM.enum['ArrowRight_1x2_DEFAULT_DEFAULT'], ArrowRight_1x2],
  [ACTUAL_ICON_TYPE_ENUM.enum['ArrowRightSmall_1x1_DEFAULT_DEFAULT'], ArrowRightSmall],
  [ACTUAL_ICON_TYPE_ENUM.enum['ArrowRightSmall_1x2_DEFAULT_DEFAULT'], ArrowRightSmall_1x2],
  [ACTUAL_ICON_TYPE_ENUM.enum['ArrowTop_1x1_DEFAULT_DEFAULT'], ArrowTop],
  [ACTUAL_ICON_TYPE_ENUM.enum['ArrowTopSmall_2x3_DEFAULT_DEFAULT'], ArrowTopSmall_2x3],
  [ACTUAL_ICON_TYPE_ENUM.enum['ArrowUp_1x1_DEFAULT_DEFAULT'], ArrowUp],
  [ACTUAL_ICON_TYPE_ENUM.enum['Basket_1x1_DEFAULT_DEFAULT'], Basket],
  [ACTUAL_ICON_TYPE_ENUM.enum['Bell_1x1_DEFAULT_DEFAULT'], Bell],
  [ACTUAL_ICON_TYPE_ENUM.enum['Blank_1x1_DEFAULT_DEFAULT'], Blank],
  [ACTUAL_ICON_TYPE_ENUM.enum['Calendar_1x1_DEFAULT_DEFAULT'], Calendar],
  [ACTUAL_ICON_TYPE_ENUM.enum['Cart_1x1_stroke_regular'], Cart_stroke_regular],
  [ACTUAL_ICON_TYPE_ENUM.enum['Cart_1x1_stroke_light'], Cart_stroke_light],
  [ACTUAL_ICON_TYPE_ENUM.enum['CellIndicator_1x1_DEFAULT_DEFAULT'], CellIndicator],
  [ACTUAL_ICON_TYPE_ENUM.enum['Close_1x1_DEFAULT_DEFAULT'], Close],
  [ACTUAL_ICON_TYPE_ENUM.enum['CloseCircle_1x1_DEFAULT_DEFAULT'], CloseCircle],
  [ACTUAL_ICON_TYPE_ENUM.enum['Copy_1x1_stroke_DEFAULT'], Copy_stroke],
  [ACTUAL_ICON_TYPE_ENUM.enum['Copy_1x1_fill_DEFAULT'], Copy_fill],
  [ACTUAL_ICON_TYPE_ENUM.enum['Delete_1x1_DEFAULT_DEFAULT'], Delete],
  [ACTUAL_ICON_TYPE_ENUM.enum['ErrorCircle_1x1_DEFAULT_DEFAULT'], ErrorCircle],
  [ACTUAL_ICON_TYPE_ENUM.enum['ErrorTriangle_1x1_DEFAULT_DEFAULT'], ErrorTriangle],
  [ACTUAL_ICON_TYPE_ENUM.enum['Filter_1x1_DEFAULT_DEFAULT'], Filter],
  [ACTUAL_ICON_TYPE_ENUM.enum['Freeze_1x1_DEFAULT_DEFAULT'], Freeze],
  [ACTUAL_ICON_TYPE_ENUM.enum['Gift_1x1_DEFAULT_DEFAULT'], Gift],
  [ACTUAL_ICON_TYPE_ENUM.enum['Heart_1x1_DEFAULT_DEFAULT'], Heart],
  [ACTUAL_ICON_TYPE_ENUM.enum['InfoCircle_1x1_DEFAULT_DEFAULT'], InfoCircle],
  [ACTUAL_ICON_TYPE_ENUM.enum['Kakao_1x1_DEFAULT_DEFAULT'], Kakao],
  [ACTUAL_ICON_TYPE_ENUM.enum['Location_1x1_stroke_DEFAULT'], Location_stroke],
  [ACTUAL_ICON_TYPE_ENUM.enum['Location_1x1_fill_DEFAULT'], Location_fill],
  [ACTUAL_ICON_TYPE_ENUM.enum['Menu_1x1_DEFAULT_DEFAULT'], Menu],
  [ACTUAL_ICON_TYPE_ENUM.enum['Minus_1x1_DEFAULT_DEFAULT'], Minus],
  [ACTUAL_ICON_TYPE_ENUM.enum['More_1x1_DEFAULT_DEFAULT'], More],
  [ACTUAL_ICON_TYPE_ENUM.enum['MoreInfo_1x1_DEFAULT_DEFAULT'], MoreInfo],
  [ACTUAL_ICON_TYPE_ENUM.enum['Pause_1x1_DEFAULT_DEFAULT'], Pause],
  [ACTUAL_ICON_TYPE_ENUM.enum['Person_1x1_stroke_DEFAULT'], Person_stroke],
  [ACTUAL_ICON_TYPE_ENUM.enum['Person_1x1_fill_DEFAULT'], Person_fill],
  [ACTUAL_ICON_TYPE_ENUM.enum['Play_1x1_DEFAULT_DEFAULT'], Play],
  [ACTUAL_ICON_TYPE_ENUM.enum['Plus_1x1_DEFAULT_DEFAULT'], Plus],
  [ACTUAL_ICON_TYPE_ENUM.enum['QRCode_1x1_DEFAULT_DEFAULT'], QRCode],
  [ACTUAL_ICON_TYPE_ENUM.enum['QuestionCircle_1x1_DEFAULT_DEFAULT'], QuestionCircle],
  [ACTUAL_ICON_TYPE_ENUM.enum['Refresh_1x1_DEFAULT_DEFAULT'], Refresh],
  [ACTUAL_ICON_TYPE_ENUM.enum['Search_1x1_DEFAULT_DEFAULT'], Search],
  [ACTUAL_ICON_TYPE_ENUM.enum['SoundOff_1x1_DEFAULT_DEFAULT'], SoundOff],
  [ACTUAL_ICON_TYPE_ENUM.enum['SoundOn_1x1_DEFAULT_DEFAULT'], SoundOn],
  [ACTUAL_ICON_TYPE_ENUM.enum['Sun_1x1_DEFAULT_DEFAULT'], Sun],
  [ACTUAL_ICON_TYPE_ENUM.enum['TextBubble_1x1_stroke_regular'], TextBubble_stroke_regular],
  [ACTUAL_ICON_TYPE_ENUM.enum['TextBubble_1x1_stroke_light'], TextBubble_stroke_light],
  [ACTUAL_ICON_TYPE_ENUM.enum['TextBubble_1x1_fill_DEFAULT'], TextBubble_fill],
  [ACTUAL_ICON_TYPE_ENUM.enum['WaterDrop_1x1_DEFAULT_DEFAULT'], WaterDrop],
  [ACTUAL_ICON_TYPE_ENUM.enum['WaterDrop_2x3_DEFAULT_DEFAULT'], WaterDrop_2x3],
  [ACTUAL_ICON_TYPE_ENUM.enum['WarnCircle_1x1_DEFAULT_DEFAULT'], WarnCircle_red],
  [ACTUAL_ICON_TYPE_ENUM.enum['CheckCircle_1x1_DEFAULT_DEFAULT'], CheckCircle_green],
  [ACTUAL_ICON_TYPE_ENUM.enum['ErrorCircle_red_1x1_DEFAULT_DEFAULT'], ErrorCircle_red],
  [ACTUAL_ICON_TYPE_ENUM.enum['Photo_1x1_stroke_regular'], Photo_stroke_regular],
  [ACTUAL_ICON_TYPE_ENUM.enum['Photo_1x1_stroke_light'], Photo_stroke_light],
]);

type IconType = z.infer<typeof ICON_TYPE_ENUM>;
type ActualIconType = z.infer<typeof ACTUAL_ICON_TYPE_ENUM>;

export { ICON_TYPE_ENUM, ACTUAL_ICON_TYPE_ENUM, ACTUAL_ICON_MAP };
export type { IconType, ActualIconType };
export * from './scheme';
